import { createContext, useContext, useState, useEffect } from "react";

export type Language = "fr" | "en";

const translations = {
  fr: {
    nav: {
      menu: "Menu",
      close: "Fermer le menu",
      account: "Compte",
      login: "Se connecter",
      register: "Créer un compte",
      resources: "Ressources",
      help: "Centre d'aide",
      faq: "FAQ",
      blog: "Blog",
      contact: "Contact",
      apiDocs: "Documentation API",
      hostedDocs: "Documentation Hosted Page",
      about: "À propos",
      about_link: "À propos",
      careers: "Carrières",
      legal: "Légal",
      terms: "Conditions d'utilisation",
      privacy: "Politique de confidentialité",
      legalNotice: "Mentions légales",
    },
    hero: {
      title1: "Vendez en ligne.",
      title2: "Encaissez instantanément.",
      desc: " est une plateforme de paiement innovante qui permet aux créateurs, entrepreneurs et commerçants de vendre leurs produits physiques ou digitaux grâce à un simple lien de paiement, et de recevoir leur argent immédiatement, en toute sécurité.",
      bullet1: "Aucun site requis.",
      bullet2: "Aucun stress technique.",
      bullet3: "Paiements locaux & internationaux.",
      cta: "Commencer maintenant",
      ctaLogin: "Se connecter",
      totalBalance: "Solde total",
      send: "Envoyer",
      receive: "Recevoir",
      topup: "Recharger",
      recentTx: "Transactions récentes",
    },
    landing: {
      onlineSalesTag: "Un lien. Plusieurs moyens de paiement.",
      onlineSalesTitle1: "VENDEZ",
      onlineSalesTitle2: "tout type de produit",
      onlineSalesDesc: "Vos clients peuvent payer avec MOBILE MONEY (MTN, ORANGE, AIRTEL, MOOV), CARTE BANCAIRE (VISA, MASTERCARD), virements locaux et autres moyens selon le pays.",
      digitalProducts: "Produits digitaux",
      files: "Fichiers",
      courses: "Formations",
      privateAccess: "Accès privés",
      services: "Services",
      autoDelivery: "Livraison automatique après paiement",
      physicalProducts: "Produits physiques",
      clientInfo: "Collecte des informations client",
      orderTracking: "Suivi des commandes",
      salesManagement: "Gestion simple des ventes",
      txHistory: "Historique complet des transactions",
      paymentLinksTag: "Liens de paiement",
      paymentLinksTitle: "Créez vos liens et partagez-les partout",
      paymentLinksDesc: "De la création du lien au retrait de vos fonds, tout devient facile. Créez en quelques secondes un lien de paiement adapté à vos besoins.",
      fixedOrFree: "Montant fixe ou libre",
      fixedOrFreeDesc: "Adaptez selon vos besoins",
      pdfFile: "Fichier PDF inclus",
      pdfFileDesc: "Joignez vos documents",
      expiry: "Date d'expiration",
      expiryDesc: "Contrôlez la validité",
      redirect: "Lien de redirection",
      redirectDesc: "Après paiement",
      feesTitle: "Des frais transparents",
      feesDesc: "Aucune surprise. Vous payez uniquement lorsque vous encaissez.",
      coverageTitle: "Couverture africaine",
      coverageDesc: "Disponible dans plus de 20 pays africains.",
      securityTitle: "Sécurité maximale",
      securityDesc: "Transactions chiffrées, données protégées.",
      ctaTitle: "Prêt à commencer ?",
      ctaDesc: "Rejoignez des milliers de marchands qui font confiance à AshTech Pay.",
      ctaBtn: "Créer un compte gratuit",
    },
    sidebar: {
      availableBalance: "Solde disponible",
      mainMenu: "Menu Principal",
      settingsSupport: "Paramètres & Support",
      administration: "Administration",
      adminPanel: "Panel Admin",
      logout: "Déconnexion",
      verified: "Vérifié",
      dashboard: "Tableau de bord",
      links: "Mes liens",
      transactions: "Transactions",
      deposit: "Dépôt",
      withdraw: "Retrait",
      send: "Envoyer",
      wallets: "Comptes",
      kyc: "KYC",
      support: "Support",
      apiKeys: "Clés API",
      settings: "Paramètres",
      fees: "Frais",
    },
    dashboard: {
      title: "Tableau de bord",
      welcome: "Bienvenue",
      mainBalance: "Solde Principal",
      accounts: "Comptes",
      quickActions: "Actions rapides",
      overview: "Vue d'ensemble",
      deposit: "Dépôt",
      withdraw: "Retrait",
      send: "Envoyer",
      paymentLink: "Lien paiement",
      allLinks: "Tous les liens",
      linkClicks: "Clics sur les liens",
      totalTransactions: "Transactions",
      totalCollected: "Total collecté",
      activeLinks: "Liens actifs",
      activity: "Activité",
      collectedAmounts: "Montants collectés",
      last7days: "Ces 7 derniers jours",
      financialSummary: "Résumé financier",
      statistics: "Statistiques",
      totalReceived: "Total reçu",
      totalSent: "Total envoyé",
      thisMonth: "Ce mois-ci",
      pending: "En attente",
      recentActivity: "Activité récente",
      recentTransactions: "Transactions récentes",
      viewAll: "Tout voir",
      noTransactions: "Aucune transaction",
      maintenance: "Maintenance en cours",
      maintenanceDesc: "La plateforme est temporairement indisponible pour maintenance.",
      // Period filter
      periodToday: "Aujourd'hui",
      periodWeek: "Cette semaine",
      periodMonth: "Ce mois-ci",
      periodLastMonth: "Mois dernier",
      periodYear: "Cette année",
      periodAll: "Tout",
      // Type labels (recent tx)
      typeDeposit: "Dépôt",
      typeWithdrawal: "Retrait",
      typeTransferIn: "Reçu",
      typeTransferOut: "Envoyé",
      typePaymentLink: "Lien de paiement",
      typeConversion: "Conversion",
      // Status
      statusCompleted: "Complété",
      statusPending: "En attente",
      statusFailed: "Échoué",
    },
    transactions: {
      title: "Transactions",
      totalCount: "transaction au total",
      totalCountPlural: "transactions au total",
      // Summary
      summaryLabel: "Résumé",
      summaryFiltered: "Résumé (filtré)",
      totalIn: "Total entrant",
      totalOut: "Total sortant",
      displayed: "Résultats affichés",
      pendingCount: "En attente",
      // Type labels
      typeDeposit: "Dépôt Mobile Money",
      typeWithdrawal: "Retrait",
      typeTransferIn: "Virement reçu",
      typeTransferOut: "Virement envoyé",
      typePaymentLink: "Lien de paiement",
      typeConversion: "Conversion",
      // Filters
      filtersLabel: "Filtres",
      searchPlaceholder: "Rechercher par montant, opérateur, référence...",
      allTypes: "Tous les types",
      typeDeposits: "Dépôts",
      typeWithdrawals: "Retraits",
      typeReceived: "Reçus",
      typeSent: "Envoyés",
      typePaymentLinks: "Liens paiement",
      typeConversions: "Conversions",
      allStatuses: "Tous les statuts",
      statusCompleted: "Réussi",
      statusPending: "En cours",
      statusFailed: "Échoué",
      statusCancelled: "Annulé",
      allCurrencies: "Toutes devises",
      clearFilters: "Effacer",
      refresh: "Actualiser",
      exportCsv: "Export CSV",
      // History
      historyLabel: "Historique",
      noTransaction: "Aucune transaction trouvée",
      noTransactionHint: "Vos transactions apparaîtront ici",
      noTransactionFiltered: "Essayez de modifier les filtres",
      clearFiltersLink: "Effacer les filtres",
      // Pagination
      page: "Page",
      of: "sur",
      results: "résultats",
      previous: "Précédent",
      next: "Suivant",
      // Dates
      today: "Aujourd'hui",
      yesterday: "Hier",
      // CSV headers
      csvDate: "Date",
      csvType: "Type",
      csvAmount: "Montant",
      csvCurrency: "Devise",
      csvStatus: "Statut",
      csvReference: "Référence",
      csvDescription: "Description",
      csvStatusCompleted: "Réussi",
      csvStatusPending: "En attente",
      csvStatusFailed: "Échoué",
    },
    deposit: {
      title: "Recharger mon compte",
      subtitle: "Ajoutez de l'argent à votre portefeuille via Mobile Money",
      currentBalance: "Solde actuel",
      noCountry: "Aucun pays ou opérateur n'est actuellement disponible. Veuillez réessayer plus tard.",
      sectionLabel: "Dépôt Mobile Money",
      cardTitle: "Nouveau dépôt",
      cardDesc: "Suivez les étapes pour recharger votre compte",
      // Steps
      stepAmount: "Montant",
      stepAmountDesc: "Entrez le montant",
      stepCountry: "Pays & Opérateur",
      stepCountryDesc: "Sélectionnez votre pays",
      stepConfirm: "Confirmation",
      stepConfirmDesc: "Vérifiez et validez",
      // Form labels
      amountLabel: "Montant à déposer",
      countryLabel: "Pays",
      operatorLabel: "Opérateur",
      phoneLabel: "Numéro de téléphone",
      descriptionLabel: "Description (optionnel)",
      selectCountry: "Sélectionner un pays",
      selectOperator: "Sélectionner un opérateur",
      noOperator: "Aucun opérateur disponible",
      // Fee
      feeLabel: "Frais",
      feeReceive: "Vous recevez",
      // Navigation
      next: "Suivant",
      back: "Retour",
      confirm: "Confirmer le dépôt",
      // Confirm dialog
      confirmTitle: "Confirmer le dépôt",
      confirmAmount: "Montant",
      confirmFee: "Frais",
      confirmReceive: "Vous recevrez",
      confirmCountry: "Pays",
      confirmOperator: "Opérateur",
      confirmPhone: "Numéro",
      // Status
      otpRequired: "Code OTP requis",
      otpSms: "Un code OTP a été envoyé par SMS sur votre téléphone.",
      otpUssd: "Composez le code USSD ci-dessous pour obtenir votre OTP.",
      otpConfirm: "Confirmer le code OTP",
      otpValidating: "Validation…",
      expiration: "Expiration",
      reference: "Référence",
      waveTitle: "Paiement Wave",
      waveDesc: "Ouvrez Wave et confirmez votre paiement, puis revenez sur cette page.",
      waveButton: "Payer avec Wave",
      processingTitle: "Traitement en cours",
      processingDesc: "Validez la demande sur votre téléphone Mobile Money",
      successTitle: "Dépôt réussi !",
      successDesc: "Votre compte a été crédité avec succès.",
      successBalance: "Nouveau solde",
      newDeposit: "Nouveau dépôt",
      failedTitle: "Paiement échoué",
      failedDesc: "La transaction n'a pas pu être complétée.",
      cancelDeposit: "Annuler",
      retry: "Réessayer",
    },
    withdraw: {
      title: "Retirer de l'argent",
      subtitle: "Retirez vos fonds vers votre compte",
      mainBalance: "Solde compte principal",
      insufficientBalance: "Solde insuffisant. Minimum :",
      unverifiedTitle: "Compte non vérifié",
      unverifiedDesc: "Pour effectuer des retraits, vous devez d'abord vérifier votre compte. La vérification permet de sécuriser vos transactions et d'accéder à toutes les fonctionnalités.",
      verifyButton: "Passer la vérification",
      // Method card
      methodLabel: "Méthode",
      methodTitle: "Mode de retrait",
      mobileMoney: "Mobile Money",
      mobileMoneyDesc: "Orange, MTN, Wave, Airtel...",
      bankTransfer: "Virement bancaire",
      bankTransferDesc: "Vers votre compte bancaire",
      comingSoon: "Bientôt disponible",
      comingSoonDesc: "Le virement bancaire sera disponible prochainement.",
      // Form card
      formLabel: "Formulaire",
      formTitle: "Détails du retrait",
      amountLabel: "Montant",
      countryLabel: "Pays (compte principal)",
      operatorLabel: "Opérateur Mobile Money",
      noOperator: "Aucun opérateur disponible",
      registeredNumber: "Numéro enregistré",
      chooseNumber: "Choisir un numéro",
      manageNumbers: "Gérer mes numéros",
      noNumberTitle: "Aucun numéro enregistré",
      noNumbers: "Aucun numéro enregistré",
      addNumber: "Ajouter un numéro",
      phoneLabel: "Numéro de téléphone",
      bankAccountLabel: "Numéro de compte bancaire",
      minAmount: "Minimum :",
      insufficientFunds: "Solde insuffisant",
      // Fee
      inputAmount: "Montant saisi",
      withdrawalFee: "Frais de retrait",
      free: "Gratuit",
      netReceive: "Net à recevoir",
      // Buttons
      requestWithdrawal: "Demander le retrait",
      submitButton: "Demander le retrait",
      feeDetails: "Détails des frais",
      // Confirm dialog
      confirmTitle: "Confirmer le retrait",
      confirmMethod: "Méthode",
      confirmCountry: "Pays",
      confirmOperator: "Opérateur",
      confirmNumber: "Numéro",
      confirmAmount: "Montant demandé",
      confirmFee: "Frais",
      confirmNet: "Net à recevoir",
      back: "Retour",
      confirm: "Confirmer",
    },
    send: {
      title: "Envoyer de l'argent",
      subtitle: "Transfert instantané ou via Mobile Money",
      subtitleUnverified: "Envoyez de l'argent à un destinataire",
      unverifiedTitle: "Compte non vérifié",
      unverifiedDesc: "Pour envoyer de l'argent, vous devez d'abord vérifier votre compte.",
      verifyButton: "Passer la vérification",
      // Transfer card
      sectionLabel: "Transfert",
      cardTitle: "Nouveau transfert",
      cardDesc: "Sélectionnez la destination pour commencer",
      debitBalance: "Solde à débiter",
      mainAccount: "Compte Principal",
      destination: "Destination",
      selectDestination: "Sélectionner la destination",
      internalTransfer: "Transfert Interne Ashtech Pay",
      loading: "Chargement...",
      // Internal
      internalFree: "Frais: 0 — Transfert gratuit et instantané",
      zeroFeeMsg: "Frais: 0 — Transfert gratuit et instantané",
      recipientLabel: "Email, téléphone ou nom d'utilisateur",
      amountLabel: "Montant",
      sendButton: "Envoyer",
      // External
      chooseDestFirst: "Choisissez une destination d'abord",
      noOperator: "Aucun opérateur disponible pour ce pays",
      operatorLabel: "Opérateur",
      recipientName: "Nom du destinataire",
      recipientPhone: "Numéro de téléphone",
      amountToSend: "Montant à envoyer",
      sendAmountLabel: "Montant à envoyer",
      minAmount: "Montant minimum:",
      maxAmount: "Montant maximum:",
      currencyMismatch: "Transaction non autorisée — Le compte sélectionné est en",
      currencyMismatchMid: "mais",
      currencyMismatchEnd: "utilise",
      currencyMismatchFix: "Veuillez choisir le bon compte.",
      sendAmount: "Envoyer",
      // Balance card
      yourBalance: "Votre solde",
      // Summary
      summaryLabel: "Récapitulatif",
      summary: "Récapitulatif",
      amountSent: "Montant à envoyer",
      summaryAmount: "Montant à envoyer",
      fees: "Frais",
      summaryFee: "Frais",
      netSent: "Net envoyé",
      summaryNet: "Net envoyé",
      balanceAfter: "Solde après transfert",
      insufficientBalance: "Solde insuffisant",
      // Benefits
      benefitsLabel: "Avantages",
      advantages: "Avantages",
      benefitFree: "Gratuit — aucun frais",
      advantageFree: "Gratuit — aucun frais",
      benefitInstant: "Instantané — crédit immédiat",
      advantageInstant: "Instantané — crédit immédiat",
      benefitSecure: "Sécurisé — compte vérifié",
      advantageSecure: "Sécurisé — compte vérifié",
      free: "Gratuit",
      // Confirm internal dialog
      confirmInternalTitle: "Confirmer le transfert interne",
      confirmRecipient: "Destinataire",
      confirmDebitAccount: "Compte débité",
      confirmAmount: "Montant",
      confirmFees: "Frais",
      confirmFee: "Frais",
      confirmFreeLabel: "Gratuit",
      // Confirm external dialog
      confirmExternalTitle: "Confirmer l'envoi",
      confirmNumber: "Numéro",
      confirmPhone: "Numéro",
      confirmCountryOperator: "Pays / Opérateur",
      confirmAmountSent: "Montant envoyé",
      confirmSentAmount: "Montant envoyé",
      confirmFeePercent: "Frais",
      confirmNetReceived: "Net reçu",
      back: "Retour",
      confirm: "Confirmer",
    },
    settings: {
      title: "Paramètres",
      subtitle: "Gérez les paramètres de votre compte",
      // Sections
      profileSection: "Profil",
      verificationSection: "Vérification",
      appearanceSection: "Apparence",
      financesSection: "Finances",
      notificationsSection: "Notifications",
      securitySection: "Sécurité & API",
      dangerSection: "Zone Danger",
      // Profile
      verified: "Vérifié",
      pendingVerif: "En attente",
      unverified: "Non vérifié",
      emailLabel: "Email",
      phoneLabel: "Téléphone",
      countryLabel: "Pays",
      // KYC
      kycTitle: "Vérification KYC",
      kycVerified: "Vérifié",
      kycPending: "En attente",
      kycComplete: "Compléter",
      // Appearance
      themeLabel: "Thème",
      themeLight: "Clair",
      themeDark: "Sombre",
      // Finances
      withdrawalNumbers: "Numéros de retrait",
      manage: "Gérer",
      // Notifications
      notifPreferences: "Préférences de notification",
      notifEmail: "Notifications email",
      notifEmailDesc: "Alertes par email",
      notifPush: "Notifications push",
      notifPushDesc: "Alertes dans le navigateur",
      notifSms: "Notifications SMS",
      notifSmsDesc: "Alertes par SMS",
      notifMarketing: "Communications marketing",
      notifMarketingDesc: "Nouvelles et promotions",
      savePrefs: "Enregistrer",
      prefsSaved: "Préférences enregistrées",
      prefsSavedDesc: "Vos préférences de notification ont été sauvegardées.",
      // Security
      changePassword: "Changer le mot de passe",
      currentPassword: "Mot de passe actuel",
      newPassword: "Nouveau mot de passe",
      confirmPassword: "Confirmer le mot de passe",
      changePasswordBtn: "Changer le mot de passe",
      apiKeysLabel: "Clés API & Développeur",
      // Danger
      deleteAccount: "Supprimer mon compte",
      deleteAccountDesc: "Action irréversible",
      deleteDialogTitle: "Supprimer votre compte définitivement",
      deleteDialogDesc: "Cette action est irréversible et supprimera toutes vos données.",
      deleteConfirmLabel: "Entrez votre nom d'utilisateur pour confirmer",
      deleteConfirmHint: "Tapez",
      deleteConfirmHint2: "pour confirmer",
      cancelDelete: "Non, annuler",
      confirmDelete: "Oui, supprimer mon compte",
      // Mutations
      profileUpdated: "Profil mis à jour",
      profileUpdatedDesc: "Nom enregistré avec succès.",
      accountDeleted: "Compte supprimé",
      accountDeletedDesc: "Votre compte a été supprimé avec succès.",
    },
    common: {
      confirm: "Confirmer",
      cancel: "Annuler",
      back: "Retour",
      save: "Enregistrer",
      edit: "Modifier",
      delete: "Supprimer",
      close: "Fermer",
      loading: "Chargement...",
      error: "Erreur",
      success: "Succès",
      amount: "Montant",
      currency: "Devise",
      country: "Pays",
      operator: "Opérateur",
      phone: "Téléphone",
      name: "Nom",
      email: "Email",
      search: "Rechercher",
      filter: "Filtrer",
      export: "Exporter",
      status: "Statut",
      date: "Date",
      type: "Type",
      completed: "Complété",
      pending: "En attente",
      failed: "Échoué",
      all: "Tous",
    },
    notifications: {
      title: "Notifications",
      markAllRead: "Tout marquer comme lu",
      noNotifications: "Aucune notification",
    },
  },

  en: {
    nav: {
      menu: "Menu",
      close: "Close menu",
      account: "Account",
      login: "Log in",
      register: "Create an account",
      resources: "Resources",
      help: "Help Center",
      faq: "FAQ",
      blog: "Blog",
      contact: "Contact",
      apiDocs: "API Documentation",
      hostedDocs: "Hosted Page Documentation",
      about: "About",
      about_link: "About",
      careers: "Careers",
      legal: "Legal",
      terms: "Terms of Service",
      privacy: "Privacy Policy",
      legalNotice: "Legal Notices",
    },
    hero: {
      title1: "Sell online.",
      title2: "Get paid instantly.",
      desc: " is an innovative payment platform that allows creators, entrepreneurs and merchants to sell their physical or digital products through a simple payment link, and receive their money immediately, safely.",
      bullet1: "No website required.",
      bullet2: "No technical hassle.",
      bullet3: "Local & international payments.",
      cta: "Get started now",
      ctaLogin: "Log in",
      totalBalance: "Total balance",
      send: "Send",
      receive: "Receive",
      topup: "Top up",
      recentTx: "Recent transactions",
    },
    landing: {
      onlineSalesTag: "One link. Multiple payment methods.",
      onlineSalesTitle1: "SELL",
      onlineSalesTitle2: "any type of product",
      onlineSalesDesc: "Your customers can pay with MOBILE MONEY (MTN, ORANGE, AIRTEL, MOOV), BANK CARD (VISA, MASTERCARD), local transfers and other methods depending on the country.",
      digitalProducts: "Digital products",
      files: "Files",
      courses: "Courses",
      privateAccess: "Private access",
      services: "Services",
      autoDelivery: "Automatic delivery after payment",
      physicalProducts: "Physical products",
      clientInfo: "Customer information collection",
      orderTracking: "Order tracking",
      salesManagement: "Simple sales management",
      txHistory: "Full transaction history",
      paymentLinksTag: "Payment links",
      paymentLinksTitle: "Create your links and share them everywhere",
      paymentLinksDesc: "From link creation to fund withdrawal, everything becomes easy. Create a payment link tailored to your needs in seconds.",
      fixedOrFree: "Fixed or open amount",
      fixedOrFreeDesc: "Adapt to your needs",
      pdfFile: "PDF file included",
      pdfFileDesc: "Attach your documents",
      expiry: "Expiry date",
      expiryDesc: "Control validity",
      redirect: "Redirect link",
      redirectDesc: "After payment",
      feesTitle: "Transparent fees",
      feesDesc: "No surprises. You only pay when you collect.",
      coverageTitle: "African coverage",
      coverageDesc: "Available in more than 20 African countries.",
      securityTitle: "Maximum security",
      securityDesc: "Encrypted transactions, protected data.",
      ctaTitle: "Ready to get started?",
      ctaDesc: "Join thousands of merchants who trust AshTech Pay.",
      ctaBtn: "Create a free account",
    },
    sidebar: {
      availableBalance: "Available balance",
      mainMenu: "Main Menu",
      settingsSupport: "Settings & Support",
      administration: "Administration",
      adminPanel: "Admin Panel",
      logout: "Log out",
      verified: "Verified",
      dashboard: "Dashboard",
      links: "My links",
      transactions: "Transactions",
      deposit: "Deposit",
      withdraw: "Withdraw",
      send: "Send",
      wallets: "Accounts",
      kyc: "KYC",
      support: "Support",
      apiKeys: "API Keys",
      settings: "Settings",
      fees: "Fees",
    },
    dashboard: {
      title: "Dashboard",
      welcome: "Welcome",
      mainBalance: "Main Balance",
      accounts: "Accounts",
      quickActions: "Quick actions",
      overview: "Overview",
      deposit: "Deposit",
      withdraw: "Withdraw",
      send: "Send",
      paymentLink: "Payment link",
      allLinks: "All links",
      linkClicks: "Link clicks",
      totalTransactions: "Transactions",
      totalCollected: "Total collected",
      activeLinks: "Active links",
      activity: "Activity",
      collectedAmounts: "Collected amounts",
      last7days: "Last 7 days",
      financialSummary: "Financial summary",
      statistics: "Statistics",
      totalReceived: "Total received",
      totalSent: "Total sent",
      thisMonth: "This month",
      pending: "Pending",
      recentActivity: "Recent activity",
      recentTransactions: "Recent transactions",
      viewAll: "View all",
      noTransactions: "No transactions",
      maintenance: "Maintenance in progress",
      maintenanceDesc: "The platform is temporarily unavailable for maintenance.",
      periodToday: "Today",
      periodWeek: "This week",
      periodMonth: "This month",
      periodLastMonth: "Last month",
      periodYear: "This year",
      periodAll: "All",
      typeDeposit: "Deposit",
      typeWithdrawal: "Withdrawal",
      typeTransferIn: "Received",
      typeTransferOut: "Sent",
      typePaymentLink: "Payment link",
      typeConversion: "Conversion",
      statusCompleted: "Completed",
      statusPending: "Pending",
      statusFailed: "Failed",
    },
    transactions: {
      title: "Transactions",
      totalCount: "transaction total",
      totalCountPlural: "transactions total",
      summaryLabel: "Summary",
      summaryFiltered: "Summary (filtered)",
      totalIn: "Total incoming",
      totalOut: "Total outgoing",
      displayed: "Results displayed",
      pendingCount: "Pending",
      typeDeposit: "Mobile Money Deposit",
      typeWithdrawal: "Withdrawal",
      typeTransferIn: "Transfer received",
      typeTransferOut: "Transfer sent",
      typePaymentLink: "Payment link",
      typeConversion: "Conversion",
      filtersLabel: "Filters",
      searchPlaceholder: "Search by amount, operator, reference...",
      allTypes: "All types",
      typeDeposits: "Deposits",
      typeWithdrawals: "Withdrawals",
      typeReceived: "Received",
      typeSent: "Sent",
      typePaymentLinks: "Payment links",
      typeConversions: "Conversions",
      allStatuses: "All statuses",
      statusCompleted: "Completed",
      statusPending: "In progress",
      statusFailed: "Failed",
      statusCancelled: "Cancelled",
      allCurrencies: "All currencies",
      clearFilters: "Clear",
      refresh: "Refresh",
      exportCsv: "Export CSV",
      historyLabel: "History",
      noTransaction: "No transactions found",
      noTransactionHint: "Your transactions will appear here",
      noTransactionFiltered: "Try adjusting the filters",
      clearFiltersLink: "Clear filters",
      page: "Page",
      of: "of",
      results: "results",
      previous: "Previous",
      next: "Next",
      today: "Today",
      yesterday: "Yesterday",
      csvDate: "Date",
      csvType: "Type",
      csvAmount: "Amount",
      csvCurrency: "Currency",
      csvStatus: "Status",
      csvReference: "Reference",
      csvDescription: "Description",
      csvStatusCompleted: "Completed",
      csvStatusPending: "Pending",
      csvStatusFailed: "Failed",
    },
    deposit: {
      title: "Top up my account",
      subtitle: "Add money to your wallet via Mobile Money",
      currentBalance: "Current balance",
      noCountry: "No country or operator is currently available. Please try again later.",
      sectionLabel: "Mobile Money Deposit",
      cardTitle: "New deposit",
      cardDesc: "Follow the steps to top up your account",
      stepAmount: "Amount",
      stepAmountDesc: "Enter the amount",
      stepCountry: "Country & Operator",
      stepCountryDesc: "Select your country",
      stepConfirm: "Confirmation",
      stepConfirmDesc: "Review and confirm",
      amountLabel: "Amount to deposit",
      countryLabel: "Country",
      operatorLabel: "Operator",
      phoneLabel: "Phone number",
      descriptionLabel: "Description (optional)",
      selectCountry: "Select a country",
      selectOperator: "Select an operator",
      noOperator: "No operator available",
      feeLabel: "Fees",
      feeReceive: "You receive",
      next: "Next",
      back: "Back",
      confirm: "Confirm deposit",
      confirmTitle: "Confirm deposit",
      confirmAmount: "Amount",
      confirmFee: "Fees",
      confirmReceive: "You will receive",
      confirmCountry: "Country",
      confirmOperator: "Operator",
      confirmPhone: "Phone number",
      otpRequired: "OTP Code required",
      otpSms: "An OTP code has been sent by SMS to your phone.",
      otpUssd: "Dial the USSD code below to get your OTP.",
      otpConfirm: "Confirm OTP code",
      otpValidating: "Validating…",
      expiration: "Expiry",
      reference: "Reference",
      waveTitle: "Wave Payment",
      waveDesc: "Open Wave and confirm your payment, then come back to this page.",
      waveButton: "Pay with Wave",
      processingTitle: "Processing",
      processingDesc: "Approve the request on your Mobile Money phone",
      successTitle: "Deposit successful!",
      successDesc: "Your account has been credited successfully.",
      successBalance: "New balance",
      newDeposit: "New deposit",
      failedTitle: "Payment failed",
      failedDesc: "The transaction could not be completed.",
      cancelDeposit: "Cancel",
      retry: "Try again",
    },
    withdraw: {
      title: "Withdraw money",
      subtitle: "Withdraw your funds to your account",
      mainBalance: "Main account balance",
      insufficientBalance: "Insufficient balance. Minimum:",
      unverifiedTitle: "Account not verified",
      unverifiedDesc: "To make withdrawals, you must first verify your account. Verification secures your transactions and unlocks all features.",
      verifyButton: "Verify account",
      methodLabel: "Method",
      methodTitle: "Withdrawal method",
      mobileMoney: "Mobile Money",
      mobileMoneyDesc: "Orange, MTN, Wave, Airtel...",
      bankTransfer: "Bank transfer",
      bankTransferDesc: "To your bank account",
      comingSoon: "Coming soon",
      comingSoonDesc: "Bank transfer will be available soon.",
      formLabel: "Form",
      formTitle: "Withdrawal details",
      amountLabel: "Amount",
      countryLabel: "Country (main account)",
      operatorLabel: "Mobile Money operator",
      noOperator: "No operator available",
      registeredNumber: "Registered number",
      chooseNumber: "Choose a number",
      manageNumbers: "Manage my numbers",
      noNumberTitle: "No registered number",
      noNumbers: "No registered number",
      addNumber: "Add a number",
      phoneLabel: "Phone number",
      bankAccountLabel: "Bank account number",
      minAmount: "Minimum:",
      insufficientFunds: "Insufficient balance",
      inputAmount: "Amount entered",
      withdrawalFee: "Withdrawal fee",
      free: "Free",
      netReceive: "Net to receive",
      requestWithdrawal: "Request withdrawal",
      submitButton: "Request withdrawal",
      feeDetails: "Fee details",
      confirmTitle: "Confirm withdrawal",
      confirmMethod: "Method",
      confirmCountry: "Country",
      confirmOperator: "Operator",
      confirmNumber: "Number",
      confirmAmount: "Requested amount",
      confirmFee: "Fees",
      confirmNet: "Net to receive",
      back: "Back",
      confirm: "Confirm",
    },
    send: {
      title: "Send money",
      subtitle: "Instant transfer or via Mobile Money",
      subtitleUnverified: "Send money to a recipient",
      unverifiedTitle: "Account not verified",
      unverifiedDesc: "To send money, you must first verify your account.",
      verifyButton: "Verify account",
      sectionLabel: "Transfer",
      cardTitle: "New transfer",
      cardDesc: "Select the destination to begin",
      debitBalance: "Balance to debit",
      mainAccount: "Main Account",
      destination: "Destination",
      selectDestination: "Select destination",
      internalTransfer: "Internal Ashtech Pay Transfer",
      loading: "Loading...",
      internalFree: "Fees: 0 — Free and instant transfer",
      zeroFeeMsg: "Fees: 0 — Free and instant transfer",
      recipientLabel: "Email, phone or username",
      amountLabel: "Amount",
      sendButton: "Send",
      chooseDestFirst: "Choose a destination first",
      noOperator: "No operator available for this country",
      operatorLabel: "Operator",
      recipientName: "Recipient name",
      recipientPhone: "Phone number",
      amountToSend: "Amount to send",
      sendAmountLabel: "Amount to send",
      minAmount: "Minimum amount:",
      maxAmount: "Maximum amount:",
      currencyMismatch: "Unauthorized transaction — Selected account is in",
      currencyMismatchMid: "but",
      currencyMismatchEnd: "uses",
      currencyMismatchFix: "Please choose the correct account.",
      sendAmount: "Send",
      yourBalance: "Your balance",
      summaryLabel: "Summary",
      summary: "Summary",
      amountSent: "Amount to send",
      summaryAmount: "Amount to send",
      fees: "Fees",
      summaryFee: "Fees",
      netSent: "Net sent",
      summaryNet: "Net sent",
      balanceAfter: "Balance after transfer",
      insufficientBalance: "Insufficient balance",
      benefitsLabel: "Benefits",
      advantages: "Benefits",
      benefitFree: "Free — no fees",
      advantageFree: "Free — no fees",
      benefitInstant: "Instant — immediate credit",
      advantageInstant: "Instant — immediate credit",
      benefitSecure: "Secure — verified account",
      advantageSecure: "Secure — verified account",
      free: "Free",
      confirmInternalTitle: "Confirm internal transfer",
      confirmRecipient: "Recipient",
      confirmDebitAccount: "Debited account",
      confirmAmount: "Amount",
      confirmFees: "Fees",
      confirmFee: "Fees",
      confirmFreeLabel: "Free",
      confirmExternalTitle: "Confirm transfer",
      confirmNumber: "Number",
      confirmPhone: "Number",
      confirmCountryOperator: "Country / Operator",
      confirmAmountSent: "Amount sent",
      confirmSentAmount: "Amount sent",
      confirmFeePercent: "Fees",
      confirmNetReceived: "Net received",
      back: "Back",
      confirm: "Confirm",
    },
    settings: {
      title: "Settings",
      subtitle: "Manage your account settings",
      profileSection: "Profile",
      verificationSection: "Verification",
      appearanceSection: "Appearance",
      financesSection: "Finances",
      notificationsSection: "Notifications",
      securitySection: "Security & API",
      dangerSection: "Danger Zone",
      verified: "Verified",
      pendingVerif: "Pending",
      unverified: "Unverified",
      emailLabel: "Email",
      phoneLabel: "Phone",
      countryLabel: "Country",
      kycTitle: "KYC Verification",
      kycVerified: "Verified",
      kycPending: "Pending",
      kycComplete: "Complete",
      themeLabel: "Theme",
      themeLight: "Light",
      themeDark: "Dark",
      withdrawalNumbers: "Withdrawal numbers",
      manage: "Manage",
      notifPreferences: "Notification preferences",
      notifEmail: "Email notifications",
      notifEmailDesc: "Email alerts",
      notifPush: "Push notifications",
      notifPushDesc: "Browser alerts",
      notifSms: "SMS notifications",
      notifSmsDesc: "SMS alerts",
      notifMarketing: "Marketing communications",
      notifMarketingDesc: "News and promotions",
      savePrefs: "Save",
      prefsSaved: "Preferences saved",
      prefsSavedDesc: "Your notification preferences have been saved.",
      changePassword: "Change password",
      currentPassword: "Current password",
      newPassword: "New password",
      confirmPassword: "Confirm password",
      changePasswordBtn: "Change password",
      apiKeysLabel: "API Keys & Developer",
      deleteAccount: "Delete my account",
      deleteAccountDesc: "Irreversible action",
      deleteDialogTitle: "Permanently delete your account",
      deleteDialogDesc: "This action is irreversible and will delete all your data.",
      deleteConfirmLabel: "Enter your username to confirm",
      deleteConfirmHint: "Type",
      deleteConfirmHint2: "to confirm",
      cancelDelete: "No, cancel",
      confirmDelete: "Yes, delete my account",
      profileUpdated: "Profile updated",
      profileUpdatedDesc: "Name saved successfully.",
      accountDeleted: "Account deleted",
      accountDeletedDesc: "Your account has been deleted successfully.",
    },
    common: {
      confirm: "Confirm",
      cancel: "Cancel",
      back: "Back",
      save: "Save",
      edit: "Edit",
      delete: "Delete",
      close: "Close",
      loading: "Loading...",
      error: "Error",
      success: "Success",
      amount: "Amount",
      currency: "Currency",
      country: "Country",
      operator: "Operator",
      phone: "Phone",
      name: "Name",
      email: "Email",
      search: "Search",
      filter: "Filter",
      export: "Export",
      status: "Status",
      date: "Date",
      type: "Type",
      completed: "Completed",
      pending: "Pending",
      failed: "Failed",
      all: "All",
    },
    notifications: {
      title: "Notifications",
      markAllRead: "Mark all as read",
      noNotifications: "No notifications",
    },
  },
} as const;

export type Translations = typeof translations.fr;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("ashtech_language");
    return (saved === "en" || saved === "fr") ? saved : "fr";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("ashtech_language", lang);
  };

  const t = translations[language] as Translations;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used inside LanguageProvider");
  return ctx;
}
