import { createContext, useContext, useState, useEffect } from "react";

export type Language = "fr" | "en";

const translations = {
  fr: {
    nav: {
      menu: "Menu",
      close: "Fermer le menu",
      account: "Compte",
      login: "Se connecter",
      register: "Créer un compte",
      resources: "Ressources",
      help: "Centre d'aide",
      faq: "FAQ",
      blog: "Blog",
      contact: "Contact",
      apiDocs: "Documentation API",
      hostedDocs: "Documentation Hosted Page",
      about: "À propos",
      about_link: "À propos",
      careers: "Carrières",
      legal: "Légal",
      terms: "Conditions d'utilisation",
      privacy: "Politique de confidentialité",
      legalNotice: "Mentions légales",
    },
    hero: {
      title1: "Vendez en ligne.",
      title2: "Encaissez instantanément.",
      desc: " est une plateforme de paiement innovante qui permet aux créateurs, entrepreneurs et commerçants de vendre leurs produits physiques ou digitaux grâce à un simple lien de paiement, et de recevoir leur argent immédiatement, en toute sécurité.",
      bullet1: "Aucun site requis.",
      bullet2: "Aucun stress technique.",
      bullet3: "Paiements locaux & internationaux.",
      cta: "Commencer maintenant",
      ctaLogin: "Se connecter",
      totalBalance: "Solde total",
      send: "Envoyer",
      receive: "Recevoir",
      topup: "Recharger",
      recentTx: "Transactions récentes",
    },
    landing: {
      onlineSalesTag: "Un lien. Plusieurs moyens de paiement.",
      onlineSalesTitle1: "VENDEZ",
      onlineSalesTitle2: "tout type de produit",
      onlineSalesDesc: "Vos clients peuvent payer avec MOBILE MONEY (MTN, ORANGE, AIRTEL, MOOV), CARTE BANCAIRE (VISA, MASTERCARD), virements locaux et autres moyens selon le pays.",
      digitalProducts: "Produits digitaux",
      files: "Fichiers",
      courses: "Formations",
      privateAccess: "Accès privés",
      services: "Services",
      autoDelivery: "Livraison automatique après paiement",
      physicalProducts: "Produits physiques",
      clientInfo: "Collecte des informations client",
      orderTracking: "Suivi des commandes",
      salesManagement: "Gestion simple des ventes",
      txHistory: "Historique complet des transactions",
      paymentLinksTag: "Liens de paiement",
      paymentLinksTitle: "Créez vos liens et partagez-les partout",
      paymentLinksDesc: "De la création du lien au retrait de vos fonds, tout devient facile. Créez en quelques secondes un lien de paiement adapté à vos besoins.",
      fixedOrFree: "Montant fixe ou libre",
      fixedOrFreeDesc: "Adaptez selon vos besoins",
      pdfFile: "Fichier PDF inclus",
      pdfFileDesc: "Joignez vos documents",
      expiry: "Date d'expiration",
      expiryDesc: "Contrôlez la validité",
      redirect: "Lien de redirection",
      redirectDesc: "Après paiement",
      feesTitle: "Des frais transparents",
      feesDesc: "Aucune surprise. Vous payez uniquement lorsque vous encaissez.",
      coverageTitle: "Couverture africaine",
      coverageDesc: "Disponible dans plus de 20 pays africains.",
      securityTitle: "Sécurité maximale",
      securityDesc: "Transactions chiffrées, données protégées.",
      ctaTitle: "Prêt à commencer ?",
      ctaDesc: "Rejoignez des milliers de marchands qui font confiance à AshTech Pay.",
      ctaBtn: "Créer un compte gratuit",
      shareTag: "Partage facile",
      shareTitle1: "DIFFUSEZ",
      shareTitle2: "vos liens de paiement partout",
      shareDesc: "Diffusez vos liens de paiement sur WhatsApp, SMS, email ou réseaux sociaux, et offrez à vos clients une expérience fluide où qu'ils soient.",
      withdrawalTag: "Retraits",
      withdrawalTitle1: "RETRAITS",
      withdrawalTitle2: "rapides et flexibles",
      withdrawalDesc: "Retirez vos fonds facilement via Mobile Money ou Carte Bancaire, avec historique détaillé et confirmation instantanée.",
      withdrawalBullet1: "Retrait vers MTN, Orange Money, Airtel Money, Wave...",
      withdrawalBullet2: "Retrait vers Visa et Mastercard",
      withdrawalBullet3: "Historique détaillé de toutes vos transactions",
      withdrawalBullet4: "Confirmation instantanée par notification",
      coverageTag2: "Portée internationale",
      coverageTitle2: "Disponible dans plus de 18 pays africains",
      coverageDesc2: "Recevez des paiements de partout dans le monde et retirez vos fonds localement via Mobile Money.",
      walletTag: "Wallet sécurisé",
      walletTitle: "Un wallet sécurisé pour gérer votre argent",
      walletDesc: "Tout ce dont vous avez besoin pour encaisser et gérer vos revenus",
      feature1title: "Solde en temps réel",
      feature1desc: "Consultez votre solde et vos revenus à tout moment depuis votre tableau de bord.",
      feature2title: "Historique complet",
      feature2desc: "Retrouvez toutes vos transactions avec des détails complets et des filtres avancés.",
      feature3title: "Retraits rapides",
      feature3desc: "Retirez vos fonds vers Mobile Money ou banque de manière sécurisée.",
      feature4title: "Frais transparents",
      feature4desc: "Aucun frais caché. Vous savez exactement ce que vous payez.",
      feature5title: "Liens de paiement",
      feature5desc: "Créez des liens personnalisés avec montant fixe ou libre, fichiers PDF, date d'expiration.",
      whyTag: "Pour qui ?",
      whyTitle: "Pour qui est Ashtech Pay ?",
      whyDesc: "Si vous vendez en ligne, Ashtech Pay est fait pour vous.",
      whyChooseTitle: "Pourquoi choisir Ashtech Pay ?",
      audience1: "Créateurs de contenu",
      audience2: "Entrepreneurs",
      audience3: "E-commerçants",
      audience4: "Formateurs",
      audience5: "Freelancers",
      audience6: "Startups",
      audience7: "PME africaines",
      benefit1title: "Transactions rapides",
      benefit1desc: "Transferts effectués en quelques secondes, pas en jours.",
      benefit2title: "Sécurité renforcée",
      benefit2desc: "Vos données et transactions sont protégées par un chiffrement de niveau bancaire.",
      benefit3title: "Interface moderne",
      benefit3desc: "Une expérience utilisateur intuitive et agréable sur tous vos appareils.",
      benefit4title: "Disponible partout",
      benefit4desc: "Accessible dans plus de 18 pays africains et en expansion.",
      benefit5title: "Support réactif",
      benefit5desc: "Notre équipe est disponible 24/7 pour répondre à vos questions.",
      howTitle1: "COMMENT",
      howTitle2: "ça marche ?",
      howDescPre: "Commencez à utiliser ",
      howDescPost: " en 4 étapes simples",
      step1title: "Créez votre lien de paiement",
      step1desc: "Ajoutez votre produit, fixez le prix et générez un lien partageable.",
      step2title: "Partagez le lien",
      step2desc: "WhatsApp, Facebook, Instagram, email ou site web.",
      step3title: "Encaissez instantanément",
      step3desc: "Le client paie. L'argent arrive directement dans votre wallet.",
      step4title: "Retirez quand vous voulez",
      step4desc: "Mobile Money, banque ou autre méthode locale.",
      secTag: "Votre confiance est notre priorité",
      secTitle1: "SÉCURITÉ",
      secTitle2: "CONFORMITÉ",
      secDesc: "applique des standards stricts de sécurité et de conformité réglementaire pour protéger chaque transaction et chaque utilisateur.",
      apiDesc: "Intégrez les paiements Mobile Money dans votre application en quelques lignes de code. Notre API couvre 22 pays africains, supporte MTN, Orange, Wave, Moov et bien d'autres opérateurs.",
      secNote: "La sécurité des utilisateurs et la conformité réglementaire sont au cœur de toutes nos opérations.",
      secLink: "Consulter notre politique AML/CFT complète →",
      sec1title: "Chiffrement SSL (HTTPS)",
      sec1desc: "Toutes les communications entre votre navigateur et nos serveurs sont chiffrées via le protocole SSL/TLS. Vos données ne peuvent pas être interceptées.",
      sec2title: "Vérification KYC",
      sec2desc: "Chaque marchand passe par une vérification d'identité (Know Your Customer) avant activation. Seuls les utilisateurs vérifiés peuvent encaisser et retirer.",
      sec3title: "Monitoring anti-fraude",
      sec3desc: "Un système de surveillance temps réel analyse chaque transaction. Toute activité anormale déclenche une alerte immédiate et un blocage préventif.",
      sec4title: "Surveillance des transactions",
      sec4desc: "Chaque paiement et retrait est journalisé, horodaté et vérifié. Vous disposez d'un historique complet et immuable de toutes vos opérations.",
      sec5title: "Politique AML/CFT",
      sec5desc: "Ashtech Pay applique une politique stricte de lutte contre le blanchiment de capitaux et le financement du terrorisme, conforme aux standards GAFI/FATF.",
      sec6title: "Partenaires agréés",
      sec6desc: "Nous travaillons exclusivement avec des partenaires de paiement reconnus et conformes — dont Swychr — garantissant la fiabilité de chaque transaction.",
      testimonialsTag: "Ce que disent nos clients",
      testimonialsTitle1: "ILS NOUS",
      testimonialsTitle2: "font confiance",
      testimonialsDesc: "Des milliers de marchands africains utilisent ASHTECH PAY pour encaisser et envoyer de l'argent rapidement.",
      apiTag: "Intégration développeur",
      apiTitle1: "API REST",
      apiTitle2: "pensée pour les développeurs africains",
      apiItem1: "SDK API direct — collectez des paiements depuis votre backend",
      apiItem2: "Hosted Payment Page — lien de paiement sans code frontend",
      apiItem3: "Webhooks temps réel pour chaque événement de paiement",
      apiItem4: "Dashboard marchand avec statistiques et historique",
      apiBtn1: "Documentation SDK",
      apiBtn2: "Hosted Payment Page",
      apiStat1sub: "supportés",
      apiStat2sub: "latence API",
      apiStat3sub: "disponibilité",
      apiStat4sub: "temps réel",
      apiResponse: "200 OK — paiement initié",
      ctaTag2: "Développez votre business sans frontières",
      ctaTitle1: "COMMENCEZ",
      ctaTitle2: "maintenant",
      ctaBtn2: "Créer un compte",
      ctaBtn3: "Créer un lien de paiement",
      footerDesc: "AshTech Pay est une fintech et ne constitue pas une institution bancaire. Les services financiers sont fournis par des partenaires bancaires agréés et régulés. Les services de paiement sont opérés en partenariat avec des prestataires de paiement autorisés, conformément aux réglementations en vigueur.",
      footerCol1: "Entreprise",
      footerCol2: "Support",
      footerCol3: "Légal",
      footerAbout: "À propos",
      footerCareers: "Carrières",
      footerBlog: "Blog",
      footerHelp: "Centre d'aide",
      footerContact: "Contact",
      footerFaq: "FAQ",
      footerTerms: "Conditions",
      footerPrivacy: "Confidentialité",
      footerLegal: "Mentions légales",
      footerCopyright: "© 2026 AshTech Pay. Tous droits réservés.",
      statTitle: "Prêt à commencer ?",
      statDesc: "Permettez à vos clients de payer avec simplicité, sécurité et rapidité sur votre site ou vos réseaux sociaux, quel que soit leur service Mobile Money.",
      stat1label: "Marchands satisfaits",
      stat2label: "Entreprises partenaires",
      stat3label: "Opérateurs Mobile Money",
      stat4label: "Pays africains",
      paymentMethodsTitle: "Modes de paiement acceptés",
      countriesTitle: "Disponible dans +18 pays africains",
      operatorsTitle: "Opérateurs de Mobile Money acceptés",
    },
    sidebar: {
      availableBalance: "Solde disponible",
      mainMenu: "Menu Principal",
      settingsSupport: "Paramètres & Support",
      administration: "Administration",
      adminPanel: "Panel Admin",
      logout: "Déconnexion",
      verified: "Vérifié",
      dashboard: "Tableau de bord",
      links: "Mes liens",
      transactions: "Transactions",
      deposit: "Dépôt",
      withdraw: "Retrait",
      send: "Envoyer",
      wallets: "Comptes",
      kyc: "KYC",
      support: "Support",
      apiKeys: "Clés API",
      settings: "Paramètres",
      fees: "Frais",
    },
    dashboard: {
      title: "Tableau de bord",
      welcome: "Bienvenue",
      mainBalance: "Solde Principal",
      accounts: "Comptes",
      quickActions: "Actions rapides",
      overview: "Vue d'ensemble",
      deposit: "Dépôt",
      withdraw: "Retrait",
      send: "Envoyer",
      paymentLink: "Lien paiement",
      allLinks: "Tous les liens",
      linkClicks: "Clics sur les liens",
      totalTransactions: "Transactions",
      totalCollected: "Total collecté",
      activeLinks: "Liens actifs",
      activity: "Activité",
      collectedAmounts: "Montants collectés",
      last7days: "Ces 7 derniers jours",
      financialSummary: "Résumé financier",
      statistics: "Statistiques",
      totalReceived: "Total reçu",
      totalSent: "Total envoyé",
      thisMonth: "Ce mois-ci",
      pending: "En attente",
      recentActivity: "Activité récente",
      recentTransactions: "Transactions récentes",
      viewAll: "Tout voir",
      noTransactions: "Aucune transaction",
      maintenance: "Maintenance en cours",
      maintenanceDesc: "La plateforme est temporairement indisponible pour maintenance.",
      // Period filter
      periodToday: "Aujourd'hui",
      periodWeek: "Cette semaine",
      periodMonth: "Ce mois-ci",
      periodLastMonth: "Mois dernier",
      periodYear: "Cette année",
      periodAll: "Tout",
      // Type labels (recent tx)
      typeDeposit: "Dépôt",
      typeWithdrawal: "Retrait",
      typeTransferIn: "Reçu",
      typeTransferOut: "Envoyé",
      typePaymentLink: "Lien de paiement",
      typeConversion: "Conversion",
      // Status
      statusCompleted: "Complété",
      statusPending: "En attente",
      statusFailed: "Échoué",
    },
    transactions: {
      title: "Transactions",
      totalCount: "transaction au total",
      totalCountPlural: "transactions au total",
      // Summary
      summaryLabel: "Résumé",
      summaryFiltered: "Résumé (filtré)",
      totalIn: "Total entrant",
      totalOut: "Total sortant",
      displayed: "Résultats affichés",
      pendingCount: "En attente",
      // Type labels
      typeDeposit: "Dépôt Mobile Money",
      typeWithdrawal: "Retrait",
      typeTransferIn: "Virement reçu",
      typeTransferOut: "Virement envoyé",
      typePaymentLink: "Lien de paiement",
      typeConversion: "Conversion",
      // Filters
      filtersLabel: "Filtres",
      searchPlaceholder: "Rechercher par montant, opérateur, référence...",
      allTypes: "Tous les types",
      typeDeposits: "Dépôts",
      typeWithdrawals: "Retraits",
      typeReceived: "Reçus",
      typeSent: "Envoyés",
      typePaymentLinks: "Liens paiement",
      typeConversions: "Conversions",
      allStatuses: "Tous les statuts",
      statusCompleted: "Réussi",
      statusPending: "En cours",
      statusFailed: "Échoué",
      statusCancelled: "Annulé",
      allCurrencies: "Toutes devises",
      clearFilters: "Effacer",
      refresh: "Actualiser",
      exportCsv: "Export CSV",
      // History
      historyLabel: "Historique",
      noTransaction: "Aucune transaction trouvée",
      noTransactionHint: "Vos transactions apparaîtront ici",
      noTransactionFiltered: "Essayez de modifier les filtres",
      clearFiltersLink: "Effacer les filtres",
      // Pagination
      page: "Page",
      of: "sur",
      results: "résultats",
      previous: "Précédent",
      next: "Suivant",
      // Dates
      today: "Aujourd'hui",
      yesterday: "Hier",
      // CSV headers
      csvDate: "Date",
      csvType: "Type",
      csvAmount: "Montant",
      csvCurrency: "Devise",
      csvStatus: "Statut",
      csvReference: "Référence",
      csvDescription: "Description",
      csvStatusCompleted: "Réussi",
      csvStatusPending: "En attente",
      csvStatusFailed: "Échoué",
    },
    deposit: {
      title: "Recharger mon compte",
      subtitle: "Ajoutez de l'argent à votre portefeuille via Mobile Money",
      currentBalance: "Solde actuel",
      noCountry: "Aucun pays ou opérateur n'est actuellement disponible. Veuillez réessayer plus tard.",
      sectionLabel: "Dépôt Mobile Money",
      cardTitle: "Nouveau dépôt",
      cardDesc: "Suivez les étapes pour recharger votre compte",
      // Steps
      stepAmount: "Montant",
      stepAmountDesc: "Entrez le montant",
      stepCountry: "Pays & Opérateur",
      stepCountryDesc: "Sélectionnez votre pays",
      stepConfirm: "Confirmation",
      stepConfirmDesc: "Vérifiez et validez",
      // Form labels
      amountLabel: "Montant à déposer",
      countryLabel: "Pays",
      operatorLabel: "Opérateur",
      phoneLabel: "Numéro de téléphone",
      descriptionLabel: "Description (optionnel)",
      selectCountry: "Sélectionner un pays",
      selectOperator: "Sélectionner un opérateur",
      noOperator: "Aucun opérateur disponible",
      // Fee
      feeLabel: "Frais",
      feeReceive: "Vous recevez",
      // Navigation
      next: "Suivant",
      back: "Retour",
      confirm: "Confirmer le dépôt",
      // Confirm dialog
      confirmTitle: "Confirmer le dépôt",
      confirmAmount: "Montant",
      confirmFee: "Frais",
      confirmReceive: "Vous recevrez",
      confirmCountry: "Pays",
      confirmOperator: "Opérateur",
      confirmPhone: "Numéro",
      // Status
      otpRequired: "Code OTP requis",
      otpSms: "Un code OTP a été envoyé par SMS sur votre téléphone.",
      otpUssd: "Composez le code USSD ci-dessous pour obtenir votre OTP.",
      otpConfirm: "Confirmer le code OTP",
      otpValidating: "Validation…",
      expiration: "Expiration",
      reference: "Référence",
      waveTitle: "Paiement Wave",
      waveDesc: "Ouvrez Wave et confirmez votre paiement, puis revenez sur cette page.",
      waveButton: "Payer avec Wave",
      processingTitle: "Traitement en cours",
      processingDesc: "Validez la demande sur votre téléphone Mobile Money",
      successTitle: "Dépôt réussi !",
      successDesc: "Votre compte a été crédité avec succès.",
      successBalance: "Nouveau solde",
      newDeposit: "Nouveau dépôt",
      failedTitle: "Paiement échoué",
      failedDesc: "La transaction n'a pas pu être complétée.",
      cancelDeposit: "Annuler",
      retry: "Réessayer",
      toastError: "Erreur",
      otpValidated: "OTP validé",
      otpProcessing: "Paiement en cours de traitement…",
      otpErrorTitle: "Erreur OTP",
      refCopied: "Référence copiée",
      refCopyFail: "Échec de la copie",
      txAutoCancel: "La transaction sera automatiquement annulée si non confirmée.",
      cancelPayment: "Annuler le paiement",
      amountReceived: "Montant reçu",
      txRef: "Référence de transaction",
      step1Question: "Quel montant souhaitez-vous déposer ?",
      step1Hint: "Entrez le montant souhaité",
      continue: "Continuer",
      step2Question: "Sélectionnez votre pays et opérateur",
      step2Hint: "Choisissez votre fournisseur Mobile Money",
      chooseCountry: "Choisir le pays",
      noCountrySelected: "Choisissez un pays d'abord",
      operatorMobileLabel: "Opérateur Mobile Money",
      step3Question: "Confirmez votre dépôt",
      step3Hint: "Entrez votre numéro et validez",
      phoneMobileLabel: "Numéro de téléphone Mobile Money",
      otpOrangeLabel: "Code OTP requis — Orange Money",
      otpOrangeInstruction: "sur votre téléphone pour obtenir votre code OTP, puis saisissez-le ci-dessous.",
      otpPlaceholder: "Votre code OTP",
      amountEntered: "Montant saisi",
      depositFeeLabel: "Frais de dépôt",
      feeFixed: "(fixe)",
      feeFree: "(Gratuit)",
      creditedLabel: "Montant crédité",
      processing: "Traitement...",
      confirmBtn: "Confirmer",
      dialogPhone: "Numéro Mobile Money",
    },
    withdraw: {
      title: "Retirer de l'argent",
      subtitle: "Retirez vos fonds vers votre compte",
      mainBalance: "Solde compte principal",
      insufficientBalance: "Solde insuffisant. Minimum :",
      unverifiedTitle: "Compte non vérifié",
      unverifiedDesc: "Pour effectuer des retraits, vous devez d'abord vérifier votre compte. La vérification permet de sécuriser vos transactions et d'accéder à toutes les fonctionnalités.",
      verifyButton: "Passer la vérification",
      // Method card
      methodLabel: "Méthode",
      methodTitle: "Mode de retrait",
      mobileMoney: "Mobile Money",
      mobileMoneyDesc: "Orange, MTN, Wave, Airtel...",
      bankTransfer: "Virement bancaire",
      bankTransferDesc: "Vers votre compte bancaire",
      comingSoon: "Bientôt disponible",
      comingSoonDesc: "Le virement bancaire sera disponible prochainement.",
      // Form card
      formLabel: "Formulaire",
      formTitle: "Détails du retrait",
      amountLabel: "Montant",
      countryLabel: "Pays (compte principal)",
      operatorLabel: "Opérateur Mobile Money",
      noOperator: "Aucun opérateur disponible",
      registeredNumber: "Numéro enregistré",
      chooseNumber: "Choisir un numéro",
      manageNumbers: "Gérer mes numéros",
      noNumberTitle: "Aucun numéro enregistré",
      noNumbers: "Aucun numéro enregistré",
      addNumber: "Ajouter un numéro",
      phoneLabel: "Numéro de téléphone",
      bankAccountLabel: "Numéro de compte bancaire",
      minAmount: "Minimum :",
      insufficientFunds: "Solde insuffisant",
      // Fee
      inputAmount: "Montant saisi",
      withdrawalFee: "Frais de retrait",
      free: "Gratuit",
      netReceive: "Net à recevoir",
      // Buttons
      requestWithdrawal: "Demander le retrait",
      submitButton: "Demander le retrait",
      feeDetails: "Détails des frais",
      // Confirm dialog
      confirmTitle: "Confirmer le retrait",
      confirmMethod: "Méthode",
      confirmCountry: "Pays",
      confirmOperator: "Opérateur",
      confirmNumber: "Numéro",
      confirmAmount: "Montant demandé",
      confirmFee: "Frais",
      confirmNet: "Net à recevoir",
      back: "Retour",
      confirm: "Confirmer",
    },
    send: {
      title: "Envoyer de l'argent",
      subtitle: "Transfert instantané ou via Mobile Money",
      subtitleUnverified: "Envoyez de l'argent à un destinataire",
      unverifiedTitle: "Compte non vérifié",
      unverifiedDesc: "Pour envoyer de l'argent, vous devez d'abord vérifier votre compte.",
      verifyButton: "Passer la vérification",
      // Transfer card
      sectionLabel: "Transfert",
      cardTitle: "Nouveau transfert",
      cardDesc: "Sélectionnez la destination pour commencer",
      debitBalance: "Solde à débiter",
      mainAccount: "Compte Principal",
      destination: "Destination",
      selectDestination: "Sélectionner la destination",
      internalTransfer: "Transfert Interne Ashtech Pay",
      loading: "Chargement...",
      // Internal
      internalFree: "Frais: 0 — Transfert gratuit et instantané",
      zeroFeeMsg: "Frais: 0 — Transfert gratuit et instantané",
      recipientLabel: "Email, téléphone ou nom d'utilisateur",
      amountLabel: "Montant",
      sendButton: "Envoyer",
      // External
      chooseDestFirst: "Choisissez une destination d'abord",
      noOperator: "Aucun opérateur disponible pour ce pays",
      operatorLabel: "Opérateur",
      recipientName: "Nom du destinataire",
      recipientPhone: "Numéro de téléphone",
      amountToSend: "Montant à envoyer",
      sendAmountLabel: "Montant à envoyer",
      minAmount: "Montant minimum:",
      maxAmount: "Montant maximum:",
      currencyMismatch: "Transaction non autorisée — Le compte sélectionné est en",
      currencyMismatchMid: "mais",
      currencyMismatchEnd: "utilise",
      currencyMismatchFix: "Veuillez choisir le bon compte.",
      sendAmount: "Envoyer",
      // Balance card
      yourBalance: "Votre solde",
      // Summary
      summaryLabel: "Récapitulatif",
      summary: "Récapitulatif",
      amountSent: "Montant à envoyer",
      summaryAmount: "Montant à envoyer",
      fees: "Frais",
      summaryFee: "Frais",
      netSent: "Net envoyé",
      summaryNet: "Net envoyé",
      balanceAfter: "Solde après transfert",
      insufficientBalance: "Solde insuffisant",
      // Benefits
      benefitsLabel: "Avantages",
      advantages: "Avantages",
      benefitFree: "Gratuit — aucun frais",
      advantageFree: "Gratuit — aucun frais",
      benefitInstant: "Instantané — crédit immédiat",
      advantageInstant: "Instantané — crédit immédiat",
      benefitSecure: "Sécurisé — compte vérifié",
      advantageSecure: "Sécurisé — compte vérifié",
      free: "Gratuit",
      // Confirm internal dialog
      confirmInternalTitle: "Confirmer le transfert interne",
      confirmRecipient: "Destinataire",
      confirmDebitAccount: "Compte débité",
      confirmAmount: "Montant",
      confirmFees: "Frais",
      confirmFee: "Frais",
      confirmFreeLabel: "Gratuit",
      // Confirm external dialog
      confirmExternalTitle: "Confirmer l'envoi",
      confirmNumber: "Numéro",
      confirmPhone: "Numéro",
      confirmCountryOperator: "Pays / Opérateur",
      confirmAmountSent: "Montant envoyé",
      confirmSentAmount: "Montant envoyé",
      confirmFeePercent: "Frais",
      confirmNetReceived: "Net reçu",
      back: "Retour",
      confirm: "Confirmer",
    },
    settings: {
      title: "Paramètres",
      subtitle: "Gérez les paramètres de votre compte",
      // Sections
      profileSection: "Profil",
      verificationSection: "Vérification",
      appearanceSection: "Apparence",
      financesSection: "Finances",
      notificationsSection: "Notifications",
      securitySection: "Sécurité & API",
      dangerSection: "Zone Danger",
      // Profile
      verified: "Vérifié",
      pendingVerif: "En attente",
      unverified: "Non vérifié",
      emailLabel: "Email",
      phoneLabel: "Téléphone",
      countryLabel: "Pays",
      // KYC
      kycTitle: "Vérification KYC",
      kycVerified: "Vérifié",
      kycPending: "En attente",
      kycComplete: "Compléter",
      // Appearance
      themeLabel: "Thème",
      themeLight: "Clair",
      themeDark: "Sombre",
      // Finances
      withdrawalNumbers: "Numéros de retrait",
      manage: "Gérer",
      // Notifications
      notifPreferences: "Préférences de notification",
      notifEmail: "Notifications email",
      notifEmailDesc: "Alertes par email",
      notifPush: "Notifications push",
      notifPushDesc: "Alertes dans le navigateur",
      notifSms: "Notifications SMS",
      notifSmsDesc: "Alertes par SMS",
      notifMarketing: "Communications marketing",
      notifMarketingDesc: "Nouvelles et promotions",
      savePrefs: "Enregistrer",
      prefsSaved: "Préférences enregistrées",
      prefsSavedDesc: "Vos préférences de notification ont été sauvegardées.",
      // Security
      changePassword: "Changer le mot de passe",
      currentPassword: "Mot de passe actuel",
      newPassword: "Nouveau mot de passe",
      confirmPassword: "Confirmer le mot de passe",
      changePasswordBtn: "Changer le mot de passe",
      apiKeysLabel: "Clés API & Développeur",
      // Danger
      deleteAccount: "Supprimer mon compte",
      deleteAccountDesc: "Action irréversible",
      deleteDialogTitle: "Supprimer votre compte définitivement",
      deleteDialogDesc: "Cette action est irréversible et supprimera toutes vos données.",
      deleteConfirmLabel: "Entrez votre nom d'utilisateur pour confirmer",
      deleteConfirmHint: "Tapez",
      deleteConfirmHint2: "pour confirmer",
      cancelDelete: "Non, annuler",
      confirmDelete: "Oui, supprimer mon compte",
      // Mutations
      profileUpdated: "Profil mis à jour",
      profileUpdatedDesc: "Nom enregistré avec succès.",
      accountDeleted: "Compte supprimé",
      accountDeletedDesc: "Votre compte a été supprimé avec succès.",
    },
    common: {
      confirm: "Confirmer",
      cancel: "Annuler",
      back: "Retour",
      save: "Enregistrer",
      edit: "Modifier",
      delete: "Supprimer",
      close: "Fermer",
      loading: "Chargement...",
      error: "Erreur",
      success: "Succès",
      amount: "Montant",
      currency: "Devise",
      country: "Pays",
      operator: "Opérateur",
      phone: "Téléphone",
      name: "Nom",
      email: "Email",
      search: "Rechercher",
      filter: "Filtrer",
      export: "Exporter",
      status: "Statut",
      date: "Date",
      type: "Type",
      completed: "Complété",
      pending: "En attente",
      failed: "Échoué",
      all: "Tous",
    },
    notifications: {
      title: "Notifications",
      markAllRead: "Tout marquer comme lu",
      noNotifications: "Aucune notification",
    },
    kyc: {
      title: "Vérification KYC",
      subtitle: "Vérifiez votre identité pour débloquer toutes les fonctionnalités",
      statusApproved: "Compte vérifié",
      statusApprovedDesc: "Votre compte est entièrement vérifié. Vous avez accès à toutes les fonctionnalités.",
      statusPending: "Vérification en cours",
      statusPendingDesc: "Votre demande est en cours d'examen. Vous serez notifié par email une fois la vérification terminée.",
      statusRejected: "Vérification rejetée",
      statusRejectedDesc: "Votre demande a été rejetée. Veuillez soumettre de nouveaux documents.",
      statusRejectedReason: "Raison :",
      statusNone: "Vérification non effectuée",
      statusNoneDesc: "Complétez votre vérification KYC pour accéder aux fonctionnalités d'envoi, de retrait et de transfert.",
      identitySection: "Identité",
      identityTitle: "Informations personnelles",
      identityDesc: "Ces informations proviennent de votre compte et ne peuvent pas être modifiées ici",
      fullNameLabel: "Nom complet",
      emailLabel: "Adresse email",
      phoneLabel: "Numéro de téléphone",
      countryLabel: "Pays",
      cityLabel: "Ville *",
      cityPlaceholder: "Ex: Douala",
      postalCodeLabel: "Code postal *",
      postalCodePlaceholder: "Ex: 00237",
      notFilled: "Non renseigné",
      documentsSection: "Documents",
      documentsTitle: "Pièce d'identité",
      documentsDesc: "Téléchargez une copie de votre pièce d'identité valide",
      documentTypeLabel: "Type de document *",
      documentTypePlaceholder: "Choisir le type de document",
      documentNumberLabel: "Numéro du document *",
      documentNumberPlaceholder: "Ex: 123456789",
      frontLabel: "Recto du document *",
      frontDesc: "Cliquez pour télécharger le recto",
      backLabel: "Verso du document *",
      backDesc: "Cliquez pour télécharger le verso",
      selfieLabel: "Selfie avec le document *",
      selfieDesc: "Prenez un selfie en tenant votre document",
      uploading: "Téléchargement en cours...",
      uploaded: "Téléchargé",
      fileFormat: "JPG, PNG, WebP - Max 5 Mo",
      activitySection: "Activité",
      activityTitle: "Informations sur l'activité",
      activityDesc: "Décrivez votre activité professionnelle ou commerciale",
      businessTypeLabel: "Type d'activité *",
      businessTypePlaceholder: "Choisir le type d'activité",
      businessTypePhysical: "Commerce physique / Service en personne",
      businessTypeOnline: "Commerce en ligne / Service numérique",
      businessCategoryLabel: "Catégorie d'activité *",
      categoryChoose: "Choisir la catégorie",
      categorySelectType: "Sélectionnez d'abord le type",
      categorySearch: "Rechercher une catégorie...",
      categoryEmpty: "Aucune catégorie trouvée.",
      businessDescLabel: "Description de l'activité *",
      businessDescPlaceholder: "Décrivez brièvement votre activité, les produits ou services que vous proposez...",
      wordsOf: "/ 250 mots",
      requiredDocs: "Documents requis",
      docFront: "Recto du document d'identité",
      docBack: "Verso du document d'identité",
      docSelfie: "Selfie avec le document",
      submitButton: "Soumettre pour vérification",
      submitting: "Envoi en cours...",
      toastSubmitted: "Demande soumise",
      toastSubmittedDesc: "Votre demande de vérification est en cours de traitement.",
      toastError: "Erreur",
      toastFileTypeError: "Type de fichier non autorisé",
      toastFileTypeDesc: "Veuillez utiliser un fichier JPG, PNG ou WebP",
      toastFileSizeError: "Fichier trop volumineux",
      toastFileSizeDesc: "La taille maximale est de 5 Mo",
      toastFileUploaded: "Fichier téléchargé",
      toastFileUploadedDesc: "Le fichier a été téléchargé avec succès",
      toastUploadError: "Erreur de téléchargement",
      toastRequiredFields: "Champs requis",
      toastRequiredFieldsDesc: "Veuillez remplir tous les champs obligatoires (ville et code postal inclus)",
      toastDescTooLong: "Description trop longue",
      toastDescTooLongPre: "La description ne peut pas dépasser 250 mots (actuellement ",
      toastDescTooLongSuf: " mots)",
      toastDocsRequired: "Documents requis",
      toastDocsRequiredDesc: "Veuillez télécharger tous les documents requis",
    },
    withdrawalNumbers: {
      title: "Numéros de retrait",
      subtitle: "Gérez vos numéros de téléphone pour les retraits (max. 2)",
      addButton: "Ajouter un numéro",
      registeredNumbers: "Numéros enregistrés",
      noNumbers: "Aucun numéro de retrait enregistré",
      noNumbersHint: "Ajoutez un numéro pour pouvoir effectuer des retraits",
      pendingApproval: "En attente d'approbation",
      requestHistory: "Historique des demandes",
      actionAdd: "Ajout",
      actionUpdate: "Modification",
      actionDelete: "Suppression",
      statusPending: "En attente",
      statusApproved: "Approuvé",
      statusRejected: "Rejeté",
      noteLabel: "Note :",
      toastDeleteTitle: "Demande envoyée",
      toastDeleteDesc: "Votre demande de suppression a été envoyée pour approbation",
      toastError: "Erreur",
    },
    addWithdrawalNumber: {
      title: "Ajouter un numéro de retrait",
      subtitle: "Sélectionnez votre opérateur et saisissez votre numéro",
      chooseOperator: "Choisir un opérateur",
      operatorsFor: "Opérateurs disponibles pour",
      yourCountry: "votre pays",
      noOperators: "Aucun opérateur disponible pour votre pays",
      contactSupport: "Contactez le support pour plus d'informations",
      numberInfo: "Informations du numéro",
      numberInfoDescPre: "Saisissez le numéro ",
      numberInfoDescSuf: " pour les retraits",
      phoneLabel: "Numéro de téléphone",
      labelLabel: "Libellé (optionnel)",
      labelPlaceholder: "ex: Principal, Secondaire",
      saveButton: "Enregistrer le numéro",
      toastAdded: "Numéro ajouté",
      toastAddedDesc: "Le numéro de retrait a été enregistré avec succès",
      toastError: "Erreur",
      toastErrorDesc: "Veuillez sélectionner un opérateur et saisir un numéro",
    },
    editWithdrawalNumber: {
      title: "Modifier le numéro de retrait",
      subtitle: "La modification nécessite une approbation admin",
      approvalRequired: "Approbation requise",
      approvalDesc: "Toute modification de numéro de retrait doit être approuvée par un administrateur pour des raisons de sécurité.",
      chooseOperator: "Choisir un opérateur",
      operatorsFor: "Opérateurs disponibles pour",
      yourCountry: "votre pays",
      noOperators: "Aucun opérateur disponible pour votre pays",
      numberInfo: "Informations du numéro",
      numberInfoDescPre: "Modifiez les informations de votre numéro ",
      phoneLabel: "Numéro de téléphone",
      labelLabel: "Libellé (optionnel)",
      labelPlaceholder: "ex: Principal, Secondaire",
      submitButton: "Soumettre la demande de modification",
      toastSent: "Demande envoyée",
      toastSentDesc: "Votre demande de modification a été envoyée pour approbation",
      toastError: "Erreur",
      toastErrorDesc: "Veuillez remplir tous les champs",
    },
    apiKeys: {
      title: "Clé API",
      subtitle: "Intégrez Ashtech Pay directement dans votre application",
      notVerifiedTitle: "Compte non vérifié",
      notVerifiedDesc: "Votre compte doit être <strong>vérifié (KYC)</strong> avant de pouvoir accéder à l'API. Complétez la vérification d'identité, puis contactez l'administrateur pour activer vos clés.",
      goKycButton: "Vérifier mon identité",
      kycStep: "Étape 1 : vérification KYC · Étape 2 : activation API par l'administrateur",
      apiNotEnabledTitle: "Accès API non activé",
      apiNotEnabledDesc: "Votre compte est <strong>vérifié</strong>, mais l'accès API n'a pas encore été activé par l'administrateur. Contactez-nous pour demander l'activation de vos clés.",
      contactAdminButton: "Contacter l'administrateur",
      apiActiveStatus: "KYC validé · En attente d'activation API par l'administrateur",
      apiBannerTitle: "API activée",
      apiBannerDesc: "Votre accès API est actif. Utilisez vos clés ci-dessous pour intégrer Ashtech Pay dans votre application.",
      modeActive: "Actif",
      hostedPageDesc: "Lien de paiement hébergé par Ashtech Pay",
      sdkDesc: "Intégration directe sans redirection",
      step1Label: "1. Configurez",
      step1Desc: "Entrez vos URLs de redirection et générez vos clés.",
      step2Label: "2. Créez un lien",
      step2Desc: "Appelez l'API pour créer un lien de paiement unique.",
      step3Label: "3. Le client paie",
      step3Desc: "Le client paie sur la page Ashtech Pay hébergée.",
      configSection: "Configuration",
      configTitle: "URLs de redirection",
      successUrlDesc: "URL vers laquelle le client sera redirigé après un paiement réussi.",
      cancelUrlDesc: "URL vers laquelle le client sera redirigé si le paiement échoue ou est annulé.",
      webhookLabel: "Webhook URL (notify_url)",
      webhookBadge: "Automatique",
      webhookDesc: "Votre serveur recevra automatiquement une notification POST à chaque paiement Hosted Page confirmé ou échoué — sans que vous ayez à le spécifier dans chaque lien.",
      saveUrlsButton: "Sauvegarder les URLs",
      savingButton: "Sauvegarde...",
      generatingButton: "Génération...",
      keysSection: "Clés générées",
      keysActive: "Actives",
      regenerateKeys: "Regénérer toutes les clés",
      regenerateWarning: "Attention — regénérer les clés invalidera les clés actuelles.",
      docButton: "Documentation",
      sdkAuthSection: "Authentification",
      sdkAuthTitle: "Votre clé API",
      sdkAuthDesc: "Utilisez cette clé pour authentifier toutes vos requêtes à l'API Ashtech Pay. Ne la partagez jamais publiquement.",
      sdkLoading: "Chargement…",
      sdkHide: "Masquer",
      sdkShow: "Afficher",
      sdkCopy: "Copier",
      sdkRegenerateWarning: "Si vous regénérez la clé, l'ancienne sera immédiatement invalidée.",
      sdkRegenerate: "Regénérer",
      sdkDocsButton: "Documentation d'intégration",
      sdkExampleTitle: "Exemple rapide",
      toastKeyCopied: "Clé copiée",
      toastKeyCopiedDescSuf: " copiée dans le presse-papiers.",
      toastRegenerated: "Clé regénérée",
      toastRegeneratedDesc: "Votre nouvelle clé API est prête. Mettez à jour votre intégration.",
      toastError: "Erreur",
      toastImpossibleRegen: "Impossible de regénérer la clé.",
      toastConfigSaved: "Configuration sauvegardée",
      toastConfigSavedDesc: "Vos clés API Hosted Page sont prêtes.",
      toastImpossibleSave: "Impossible de sauvegarder.",
      toastApiKeyCopied: "Clé copiée",
      toastApiKeyCopiedDesc: "La clé API a été copiée dans le presse-papiers.",
    },
    kycVerified: {
      title: "Compte déjà vérifié",
      desc: "Votre compte est déjà vérifié. Vous avez accès à toutes les fonctionnalités de la plateforme.",
      updateQuestion: "Souhaitez-vous mettre à jour vos informations KYC ?",
      noBack: "Non, retourner au tableau de bord",
      yesUpdate: "Oui, mettre à jour",
    },
    wallets: {
      title: "Mes Comptes",
      subtitle: "Gérez vos portefeuilles multi-devises",
      addAccount: "Ajouter un compte",
      alertDesc: "Les paiements reçus sont crédités dans le wallet correspondant à la devise du paiement. Utilisez la conversion pour transférer entre vos comptes.",
      walletsLabel: "Portefeuilles",
      principal: "Principal",
      balance: "Solde",
      requestConversion: "Demander une conversion",
      disableTooltip: "Désactiver ce compte",
      disableTitle: "Désactiver ce compte",
      conversionDone: "Conversion effectuée",
      conversionDoneDescPre: "Votre conversion de ",
      conversionDoneDescMid: " vers ",
      conversionDoneDescSuf: " a été traitée avec succès.",
      convertDialogTitle: "Conversion de devises",
      convertDialogDesc: "Convertissez vos fonds instantanément. Les frais de conversion sont appliqués automatiquement.",
      fromAccount: "Compte source (à débiter)",
      toAccount: "Compte cible (à créditer)",
      convertAmountLabel: "Montant à convertir",
      insufficientPre: "Solde insuffisant. Disponible : ",
      grossAmount: "Montant brut",
      conversionFee: "Frais de conversion (estimé)",
      youReceiveAbout: "Vous recevrez environ",
      rateNote: "Le taux final peut varier légèrement.",
      cancel: "Annuler",
      convertNow: "Convertir maintenant",
      addDialogTitle: "Ajouter un compte",
      addDialogDesc: "Ouvrez un nouveau compte dans une autre devise. Le compte sera initialisé avec un solde de 0.",
      currencyLabel: "Devise",
      chooseCurrency: "Choisir une devise",
      create: "Créer",
      disableWithBalancePre: "Ce compte ",
      disableWithBalanceMid: " contient un solde de ",
      disableWithBalanceSuf: ". Ce montant sera définitivement perdu si vous désactivez ce compte. Voulez-vous vraiment continuer ?",
      disableLose: "Ce montant sera définitivement perdu",
      disableNoBalancePre: "Voulez-vous désactiver le compte ",
      disableNoBalanceSuf: " ? Ce compte sera supprimé de votre liste.",
      disableButton: "Désactiver et perdre le solde",
      disableButtonSimple: "Désactiver",
      toastCreated: "Compte créé",
      toastCreatedDescPre: "Compte ",
      toastCreatedDescSuf: " créé avec succès",
      toastDisabled: "Compte désactivé",
      toastDisabledDescPre: "Le compte ",
      toastDisabledDescSuf: " a été supprimé",
      toastError: "Erreur",
    },
    support: {
      title: "Support",
      subtitle: "Comment pouvons-nous vous aider?",
      contactSection: "Nous contacter",
      chatTitle: "Chat en direct",
      chatDesc: "Réponse en quelques minutes",
      whatsappChannelTitle: "Rejoindre notre chaîne WhatsApp",
      whatsappChannelDesc: "Restez informé des dernières actualités et mises à jour d'Ashtech Pay",
      joinChannel: "Rejoindre la chaîne",
      myConversationsSection: "Mes conversations",
      seeAll: "Voir toutes les conversations",
      faqSection: "Questions fréquentes",
      faq1Q: "Comment recharger mon compte?",
      faq1A: "Allez dans Dépôt et choisissez votre mode de paiement préféré (Mobile Money ou Crypto).",
      faq2Q: "Combien de temps prend un retrait?",
      faq2A: "Les retraits sont traités en 24h ouvrées. Mobile Money est généralement plus rapide (quelques minutes).",
      faq3Q: "Comment créer un lien de paiement?",
      faq3A: "Allez dans 'Mes liens', cliquez sur 'Nouveau lien' et remplissez le formulaire.",
      faq4Q: "Quels sont les frais de transaction?",
      faq4A: "Les transferts entre utilisateurs Ashtech Pay sont gratuits. Des frais s'appliquent pour les retraits externes.",
      supportOnline: "Support en ligne",
      supportOffline: "Support hors ligne",
      close: "Clôturer",
      newChat: "Nouveau",
      myConversations: "Mes conversations",
      noConversations: "Aucune conversation",
      startConversation: "Démarrer une conversation",
      noMessages: "Aucun message",
      closedConversation: "Cette conversation est clôturée",
      messagePlaceholder: "Écrivez votre message...",
      newConversationTitle: "Nouvelle conversation",
      newConversationDesc: "Décrivez votre problème et notre équipe vous répondra rapidement.",
      subjectLabel: "Sujet *",
      subjectPlaceholder: "Ex: Problème de dépôt",
      messageLabel: "Message *",
      messagePlaceholder2: "Décrivez votre problème en détail...",
      send: "Envoyer",
      sending: "Envoi...",
      cancel: "Annuler",
      requiredFields: "Champs requis",
      requiredFieldsDesc: "Veuillez remplir tous les champs.",
      ticketClosed: "Ticket clôturé",
      ticketClosedDesc: "La conversation a été clôturée.",
      errorCreate: "Impossible de créer le ticket.",
      errorSend: "Impossible d'envoyer le message.",
      statusOpen: "Ouvert",
      statusInProgress: "En cours",
      statusResolved: "Résolu",
      statusClosed: "Clôturé",
    },
    links: {
      title: "Mes liens de paiement",
      subtitle: "Gérez vos liens et analysez vos performances",
      newLink: "Nouveau lien",
      recentLinks: "Liens récents",
      allYourLinks: "Tous vos",
      linksWord: "liens",
      freeAmount: "Montant libre",
      clicks: "clics",
      showLess: "Afficher moins",
      seeMore: "Voir",
      moreLinks: "autres",
      allLinks: "Tous les liens",
      periodToday: "Aujourd'hui",
      periodWeek: "Cette semaine",
      periodMonth: "Ce mois-ci",
      periodLastMonth: "Mois dernier",
      periodYear: "Cette année",
      periodAll: "Tout",
      statClicks: "Clics sur les liens",
      statTransactions: "Transactions",
      statCollected: "Total collecté",
      statConversion: "Taux de conversion",
      trendVsPrevious: "+12% vs période précédente",
      trendTransactions: "+8% vs période précédente",
      tabAnalytics: "Analytiques",
      tabPayments: "Paiements",
      tabLinks: "Liens",
      analyticsSection: "Analytiques",
      chartTitle: "Montants collectés par période",
      chartDescWeek: "Cette semaine",
      chartDescMonths: "Ces 6 derniers mois",
      geoSection: "Géographie",
      geoTitle: "Pays principaux",
      methodsSection: "Méthodes",
      methodsTitle: "Sources de paiement",
      methodsDesc: "Répartition des paiements par méthode",
      methodMobileMoney: "Mobile Money",
      methodCard: "Carte bancaire",
      methodPaypal: "PayPal",
      methodOther: "Autre",
      noData: "Aucune donnée",
      paymentsSection: "Paiements",
      paymentsTitle: "Paiements reçus",
      paymentsDesc: "Tous les paiements effectués via vos liens",
      noPayments: "Aucun paiement reçu pour le moment",
      statusCompleted: "Complété",
      statusPending: "En attente",
      statusFailed: "Échoué",
      amountPaid: "Montant payé:",
      fee: "frais",
      ref: "Réf:",
      allLinksSection: "Tous les liens",
      noLinks: "Aucun lien de paiement créé",
      createFirstLink: "Créer votre premier lien",
      deactivate: "Désactiver",
      activate: "Activer",
      deleteConfirm: "Êtes-vous sûr de vouloir supprimer ce lien définitivement ?",
      qrModalDesc: "Scannez ce code pour accéder au lien de paiement",
      copyLink: "Copier le lien",
      toastCopied: "Lien copié",
      toastCopiedDesc: "Le lien a été copié dans le presse-papier",
      toastDeleted: "Lien supprimé",
      toastDeletedDesc: "Le lien a été supprimé définitivement",
      toastPdf: "PDF téléchargé",
      toastPdfDesc: "Le rapport a été généré avec succès",
      toastLinkCreated: "Lien créé",
      toastLinkCreatedDesc: "Votre lien de paiement a été créé avec succès",
      toastLinkUpdated: "Lien modifié",
      toastLinkUpdatedDesc: "Les modifications ont été enregistrées",
      toastError: "Erreur",
      toastUploadError: "Erreur upload image",
      createDialogTitle: "Créer un lien de paiement",
      createDialogDesc: "Créez un lien partageable pour recevoir des paiements",
      editDialogTitle: "Modifier le lien de paiement",
      editDialogDesc: "Modifiez les informations de votre lien",
      formTitle: "Titre *",
      formTitlePlaceholder: "Ex: Paiement commande #123",
      formDesc: "Description (optionnel)",
      formDescPlaceholder: "Description du paiement...",
      formSlug: "URL personnalisée (optionnel)",
      formSlugHint: "Laissez vide pour générer automatiquement",
      formImage: "Image (optionnel)",
      formImageDesc: "Cette image s'affichera sur la page de paiement",
      formImageUpload: "Choisir une image",
      formImageAdd: "Cliquez pour ajouter une image",
      formPdf: "Lien PDF (optionnel)",
      formPdfDesc: "Ce PDF sera envoyé au client uniquement après paiement réussi",
      formPdfDelivery: "Livraison PDF après paiement",
      formPdfDeliveryDesc: "Le client recevra ce lien PDF après avoir payé avec succès",
      formAmountType: "Type de montant",
      formFixed: "Montant fixe défini par vous",
      formFree: "Montant libre choisi par le payeur",
      formAmount: "Montant",
      formExpiry: "Date d'expiration (optionnel)",
      formRedirect: "URL de redirection après paiement (optionnel)",
      formCreateButton: "Créer le lien",
      formSaveButton: "Enregistrer les modifications",
      pdfReportTitle: "Rapport du lien de paiement",
      pdfFixed: "Montant fixe",
      pdfFree: "Variable",
      pdfActive: "Actif",
      pdfInactive: "Inactif",
      qrTitle: "QR Code",
      chartAmount: "Montant",
      pmtShort: "pmt.",
      cancel: "Annuler",
    },
    login: {
      title: "Connexion",
      emailLabel: "Email ou Téléphone",
      emailPlaceholder: "votreemail@exemple.com ou +237...",
      passwordLabel: "Mot de passe",
      forgotPassword: "Mot de passe oublié ?",
      submit: "Se connecter",
      submitting: "Connexion...",
      noAccount: "Pas encore de compte ?",
      createAccount: "Créer un compte",
      home: "Accueil",
      toastSuccess: "Connexion réussie",
      toastSuccessDescPre: "Bienvenue, ",
      toastError: "Erreur de connexion",
      toastErrorDesc: "Identifiants incorrects",
    },
    register: {
      title: "Créer un compte",
      fullName: "Nom complet",
      username: "Nom d'utilisateur",
      email: "Email",
      phone: "Téléphone",
      country: "Pays",
      password: "Mot de passe",
      confirmPassword: "Confirmer le mot de passe",
      submit: "Créer mon compte",
      submitting: "Création...",
      hasAccount: "Déjà un compte ?",
      login: "Se connecter",
      home: "Accueil",
      toastSuccess: "Inscription réussie",
      toastSuccessDescPre: "Bienvenue sur Ashtech Pay, ",
      toastError: "Erreur d'inscription",
      toastErrorDesc: "Une erreur est survenue",
      errorNoCountry: "Veuillez sélectionner un pays",
      errorCountry: "Erreur",
      passwordMinError: "Le mot de passe doit contenir au moins 6 caractères",
      passwordMismatch: "Les mots de passe ne correspondent pas",
    },
  },

  en: {
    nav: {
      menu: "Menu",
      close: "Close menu",
      account: "Account",
      login: "Log in",
      register: "Create an account",
      resources: "Resources",
      help: "Help Center",
      faq: "FAQ",
      blog: "Blog",
      contact: "Contact",
      apiDocs: "API Documentation",
      hostedDocs: "Hosted Page Documentation",
      about: "About",
      about_link: "About",
      careers: "Careers",
      legal: "Legal",
      terms: "Terms of Service",
      privacy: "Privacy Policy",
      legalNotice: "Legal Notices",
    },
    hero: {
      title1: "Sell online.",
      title2: "Get paid instantly.",
      desc: " is an innovative payment platform that allows creators, entrepreneurs and merchants to sell their physical or digital products through a simple payment link, and receive their money immediately, safely.",
      bullet1: "No website required.",
      bullet2: "No technical hassle.",
      bullet3: "Local & international payments.",
      cta: "Get started now",
      ctaLogin: "Log in",
      totalBalance: "Total balance",
      send: "Send",
      receive: "Receive",
      topup: "Top up",
      recentTx: "Recent transactions",
    },
    landing: {
      onlineSalesTag: "One link. Multiple payment methods.",
      onlineSalesTitle1: "SELL",
      onlineSalesTitle2: "any type of product",
      onlineSalesDesc: "Your customers can pay with MOBILE MONEY (MTN, ORANGE, AIRTEL, MOOV), BANK CARD (VISA, MASTERCARD), local transfers and other methods depending on the country.",
      digitalProducts: "Digital products",
      files: "Files",
      courses: "Courses",
      privateAccess: "Private access",
      services: "Services",
      autoDelivery: "Automatic delivery after payment",
      physicalProducts: "Physical products",
      clientInfo: "Customer information collection",
      orderTracking: "Order tracking",
      salesManagement: "Simple sales management",
      txHistory: "Full transaction history",
      paymentLinksTag: "Payment links",
      paymentLinksTitle: "Create your links and share them everywhere",
      paymentLinksDesc: "From link creation to fund withdrawal, everything becomes easy. Create a payment link tailored to your needs in seconds.",
      fixedOrFree: "Fixed or open amount",
      fixedOrFreeDesc: "Adapt to your needs",
      pdfFile: "PDF file included",
      pdfFileDesc: "Attach your documents",
      expiry: "Expiry date",
      expiryDesc: "Control validity",
      redirect: "Redirect link",
      redirectDesc: "After payment",
      feesTitle: "Transparent fees",
      feesDesc: "No surprises. You only pay when you collect.",
      coverageTitle: "African coverage",
      coverageDesc: "Available in more than 20 African countries.",
      securityTitle: "Maximum security",
      securityDesc: "Encrypted transactions, protected data.",
      ctaTitle: "Ready to get started?",
      ctaDesc: "Join thousands of merchants who trust AshTech Pay.",
      ctaBtn: "Create a free account",
      shareTag: "Easy sharing",
      shareTitle1: "SHARE",
      shareTitle2: "your payment links everywhere",
      shareDesc: "Share your payment links on WhatsApp, SMS, email or social media, and give your customers a smooth experience wherever they are.",
      withdrawalTag: "Withdrawals",
      withdrawalTitle1: "FAST",
      withdrawalTitle2: "and flexible withdrawals",
      withdrawalDesc: "Withdraw your funds easily via Mobile Money or Bank Card, with detailed history and instant confirmation.",
      withdrawalBullet1: "Withdraw to MTN, Orange Money, Airtel Money, Wave...",
      withdrawalBullet2: "Withdraw to Visa and Mastercard",
      withdrawalBullet3: "Detailed history of all your transactions",
      withdrawalBullet4: "Instant confirmation by notification",
      coverageTag2: "International reach",
      coverageTitle2: "Available in more than 18 African countries",
      coverageDesc2: "Receive payments from anywhere in the world and withdraw locally via Mobile Money.",
      walletTag: "Secure wallet",
      walletTitle: "A secure wallet to manage your money",
      walletDesc: "Everything you need to collect and manage your revenue",
      feature1title: "Real-time balance",
      feature1desc: "Check your balance and earnings at any time from your dashboard.",
      feature2title: "Full history",
      feature2desc: "Find all your transactions with complete details and advanced filters.",
      feature3title: "Fast withdrawals",
      feature3desc: "Withdraw your funds to Mobile Money or bank securely.",
      feature4title: "Transparent fees",
      feature4desc: "No hidden fees. You know exactly what you pay.",
      feature5title: "Payment links",
      feature5desc: "Create custom links with fixed or free amount, PDF files, expiration date.",
      whyTag: "Who is it for?",
      whyTitle: "Who is Ashtech Pay for?",
      whyDesc: "If you sell online, Ashtech Pay is made for you.",
      whyChooseTitle: "Why choose Ashtech Pay?",
      audience1: "Content creators",
      audience2: "Entrepreneurs",
      audience3: "E-merchants",
      audience4: "Trainers",
      audience5: "Freelancers",
      audience6: "Startups",
      audience7: "African SMEs",
      benefit1title: "Fast transactions",
      benefit1desc: "Transfers completed in seconds, not days.",
      benefit2title: "Enhanced security",
      benefit2desc: "Your data and transactions are protected by bank-level encryption.",
      benefit3title: "Modern interface",
      benefit3desc: "An intuitive and enjoyable user experience on all your devices.",
      benefit4title: "Available everywhere",
      benefit4desc: "Accessible in more than 18 African countries and expanding.",
      benefit5title: "Responsive support",
      benefit5desc: "Our team is available 24/7 to answer your questions.",
      howTitle1: "HOW",
      howTitle2: "does it work?",
      howDescPre: "Start using ",
      howDescPost: " in 4 simple steps",
      step1title: "Create your payment link",
      step1desc: "Add your product, set the price and generate a shareable link.",
      step2title: "Share the link",
      step2desc: "WhatsApp, Facebook, Instagram, email or website.",
      step3title: "Collect instantly",
      step3desc: "The customer pays. The money goes directly to your wallet.",
      step4title: "Withdraw whenever you want",
      step4desc: "Mobile Money, bank or other local method.",
      secTag: "Your trust is our priority",
      secTitle1: "SECURITY",
      secTitle2: "COMPLIANCE",
      secDesc: "applies strict security and regulatory compliance standards to protect every transaction and every user.",
      apiDesc: "Integrate Mobile Money payments into your application in a few lines of code. Our API covers 22 African countries, supports MTN, Orange, Wave, Moov and many other operators.",
      secNote: "User security and regulatory compliance are at the core of all our operations.",
      secLink: "View our complete AML/CFT policy →",
      sec1title: "SSL Encryption (HTTPS)",
      sec1desc: "All communications between your browser and our servers are encrypted via the SSL/TLS protocol. Your data cannot be intercepted.",
      sec2title: "KYC Verification",
      sec2desc: "Each merchant goes through identity verification (Know Your Customer) before activation. Only verified users can collect and withdraw.",
      sec3title: "Anti-fraud monitoring",
      sec3desc: "A real-time monitoring system analyzes every transaction. Any abnormal activity triggers an immediate alert and preventive block.",
      sec4title: "Transaction surveillance",
      sec4desc: "Each payment and withdrawal is logged, timestamped and verified. You have a complete and immutable history of all your operations.",
      sec5title: "AML/CFT Policy",
      sec5desc: "Ashtech Pay applies a strict policy against money laundering and terrorist financing, compliant with FATF standards.",
      sec6title: "Approved partners",
      sec6desc: "We work exclusively with recognized and compliant payment partners — including Swychr — guaranteeing the reliability of every transaction.",
      testimonialsTag: "What our customers say",
      testimonialsTitle1: "THEY",
      testimonialsTitle2: "trust us",
      testimonialsDesc: "Thousands of African merchants use ASHTECH PAY to collect and send money quickly.",
      apiTag: "Developer integration",
      apiTitle1: "REST API",
      apiTitle2: "designed for African developers",
      apiItem1: "Direct API SDK — collect payments from your backend",
      apiItem2: "Hosted Payment Page — payment link without frontend code",
      apiItem3: "Real-time webhooks for each payment event",
      apiItem4: "Merchant dashboard with statistics and history",
      apiBtn1: "SDK Documentation",
      apiBtn2: "Hosted Payment Page",
      apiStat1sub: "supported",
      apiStat2sub: "API latency",
      apiStat3sub: "uptime",
      apiStat4sub: "real-time",
      apiResponse: "200 OK — payment initiated",
      ctaTag2: "Grow your business without borders",
      ctaTitle1: "START",
      ctaTitle2: "now",
      ctaBtn2: "Create an account",
      ctaBtn3: "Create a payment link",
      footerDesc: "AshTech Pay is a fintech and does not constitute a banking institution. Financial services are provided by licensed and regulated banking partners. Payment services are operated in partnership with authorized payment providers, in accordance with applicable regulations.",
      footerCol1: "Company",
      footerCol2: "Support",
      footerCol3: "Legal",
      footerAbout: "About",
      footerCareers: "Careers",
      footerBlog: "Blog",
      footerHelp: "Help center",
      footerContact: "Contact",
      footerFaq: "FAQ",
      footerTerms: "Terms",
      footerPrivacy: "Privacy",
      footerLegal: "Legal notice",
      footerCopyright: "© 2026 AshTech Pay. All rights reserved.",
      statTitle: "Ready to start?",
      statDesc: "Let your customers pay with simplicity, security and speed on your website or social media, regardless of their Mobile Money service.",
      stat1label: "Satisfied merchants",
      stat2label: "Partner companies",
      stat3label: "Mobile Money operators",
      stat4label: "African countries",
      paymentMethodsTitle: "Accepted payment methods",
      countriesTitle: "Available in +18 African countries",
      operatorsTitle: "Accepted Mobile Money operators",
    },
    sidebar: {
      availableBalance: "Available balance",
      mainMenu: "Main Menu",
      settingsSupport: "Settings & Support",
      administration: "Administration",
      adminPanel: "Admin Panel",
      logout: "Log out",
      verified: "Verified",
      dashboard: "Dashboard",
      links: "My links",
      transactions: "Transactions",
      deposit: "Deposit",
      withdraw: "Withdraw",
      send: "Send",
      wallets: "Accounts",
      kyc: "KYC",
      support: "Support",
      apiKeys: "API Keys",
      settings: "Settings",
      fees: "Fees",
    },
    dashboard: {
      title: "Dashboard",
      welcome: "Welcome",
      mainBalance: "Main Balance",
      accounts: "Accounts",
      quickActions: "Quick actions",
      overview: "Overview",
      deposit: "Deposit",
      withdraw: "Withdraw",
      send: "Send",
      paymentLink: "Payment link",
      allLinks: "All links",
      linkClicks: "Link clicks",
      totalTransactions: "Transactions",
      totalCollected: "Total collected",
      activeLinks: "Active links",
      activity: "Activity",
      collectedAmounts: "Collected amounts",
      last7days: "Last 7 days",
      financialSummary: "Financial summary",
      statistics: "Statistics",
      totalReceived: "Total received",
      totalSent: "Total sent",
      thisMonth: "This month",
      pending: "Pending",
      recentActivity: "Recent activity",
      recentTransactions: "Recent transactions",
      viewAll: "View all",
      noTransactions: "No transactions",
      maintenance: "Maintenance in progress",
      maintenanceDesc: "The platform is temporarily unavailable for maintenance.",
      periodToday: "Today",
      periodWeek: "This week",
      periodMonth: "This month",
      periodLastMonth: "Last month",
      periodYear: "This year",
      periodAll: "All",
      typeDeposit: "Deposit",
      typeWithdrawal: "Withdrawal",
      typeTransferIn: "Received",
      typeTransferOut: "Sent",
      typePaymentLink: "Payment link",
      typeConversion: "Conversion",
      statusCompleted: "Completed",
      statusPending: "Pending",
      statusFailed: "Failed",
    },
    transactions: {
      title: "Transactions",
      totalCount: "transaction total",
      totalCountPlural: "transactions total",
      summaryLabel: "Summary",
      summaryFiltered: "Summary (filtered)",
      totalIn: "Total incoming",
      totalOut: "Total outgoing",
      displayed: "Results displayed",
      pendingCount: "Pending",
      typeDeposit: "Mobile Money Deposit",
      typeWithdrawal: "Withdrawal",
      typeTransferIn: "Transfer received",
      typeTransferOut: "Transfer sent",
      typePaymentLink: "Payment link",
      typeConversion: "Conversion",
      filtersLabel: "Filters",
      searchPlaceholder: "Search by amount, operator, reference...",
      allTypes: "All types",
      typeDeposits: "Deposits",
      typeWithdrawals: "Withdrawals",
      typeReceived: "Received",
      typeSent: "Sent",
      typePaymentLinks: "Payment links",
      typeConversions: "Conversions",
      allStatuses: "All statuses",
      statusCompleted: "Completed",
      statusPending: "In progress",
      statusFailed: "Failed",
      statusCancelled: "Cancelled",
      allCurrencies: "All currencies",
      clearFilters: "Clear",
      refresh: "Refresh",
      exportCsv: "Export CSV",
      historyLabel: "History",
      noTransaction: "No transactions found",
      noTransactionHint: "Your transactions will appear here",
      noTransactionFiltered: "Try adjusting the filters",
      clearFiltersLink: "Clear filters",
      page: "Page",
      of: "of",
      results: "results",
      previous: "Previous",
      next: "Next",
      today: "Today",
      yesterday: "Yesterday",
      csvDate: "Date",
      csvType: "Type",
      csvAmount: "Amount",
      csvCurrency: "Currency",
      csvStatus: "Status",
      csvReference: "Reference",
      csvDescription: "Description",
      csvStatusCompleted: "Completed",
      csvStatusPending: "Pending",
      csvStatusFailed: "Failed",
    },
    deposit: {
      title: "Top up my account",
      subtitle: "Add money to your wallet via Mobile Money",
      currentBalance: "Current balance",
      noCountry: "No country or operator is currently available. Please try again later.",
      sectionLabel: "Mobile Money Deposit",
      cardTitle: "New deposit",
      cardDesc: "Follow the steps to top up your account",
      stepAmount: "Amount",
      stepAmountDesc: "Enter the amount",
      stepCountry: "Country & Operator",
      stepCountryDesc: "Select your country",
      stepConfirm: "Confirmation",
      stepConfirmDesc: "Review and confirm",
      amountLabel: "Amount to deposit",
      countryLabel: "Country",
      operatorLabel: "Operator",
      phoneLabel: "Phone number",
      descriptionLabel: "Description (optional)",
      selectCountry: "Select a country",
      selectOperator: "Select an operator",
      noOperator: "No operator available",
      feeLabel: "Fees",
      feeReceive: "You receive",
      next: "Next",
      back: "Back",
      confirm: "Confirm deposit",
      confirmTitle: "Confirm deposit",
      confirmAmount: "Amount",
      confirmFee: "Fees",
      confirmReceive: "You will receive",
      confirmCountry: "Country",
      confirmOperator: "Operator",
      confirmPhone: "Phone number",
      otpRequired: "OTP Code required",
      otpSms: "An OTP code has been sent by SMS to your phone.",
      otpUssd: "Dial the USSD code below to get your OTP.",
      otpConfirm: "Confirm OTP code",
      otpValidating: "Validating…",
      expiration: "Expiry",
      reference: "Reference",
      waveTitle: "Wave Payment",
      waveDesc: "Open Wave and confirm your payment, then come back to this page.",
      waveButton: "Pay with Wave",
      processingTitle: "Processing",
      processingDesc: "Approve the request on your Mobile Money phone",
      successTitle: "Deposit successful!",
      successDesc: "Your account has been credited successfully.",
      successBalance: "New balance",
      newDeposit: "New deposit",
      failedTitle: "Payment failed",
      failedDesc: "The transaction could not be completed.",
      cancelDeposit: "Cancel",
      retry: "Try again",
      toastError: "Error",
      otpValidated: "OTP confirmed",
      otpProcessing: "Payment being processed…",
      otpErrorTitle: "OTP Error",
      refCopied: "Reference copied",
      refCopyFail: "Copy failed",
      txAutoCancel: "The transaction will be automatically cancelled if not confirmed.",
      cancelPayment: "Cancel payment",
      amountReceived: "Amount received",
      txRef: "Transaction reference",
      step1Question: "How much would you like to deposit?",
      step1Hint: "Enter the desired amount",
      continue: "Continue",
      step2Question: "Select your country and operator",
      step2Hint: "Choose your Mobile Money provider",
      chooseCountry: "Choose country",
      noCountrySelected: "Choose a country first",
      operatorMobileLabel: "Mobile Money Operator",
      step3Question: "Confirm your deposit",
      step3Hint: "Enter your number and confirm",
      phoneMobileLabel: "Mobile Money phone number",
      otpOrangeLabel: "OTP Code required — Orange Money",
      otpOrangeInstruction: "on your phone to get your OTP code, then enter it below.",
      otpPlaceholder: "Your OTP code",
      amountEntered: "Amount entered",
      depositFeeLabel: "Deposit fee",
      feeFixed: "(fixed)",
      feeFree: "(Free)",
      creditedLabel: "Credited amount",
      processing: "Processing...",
      confirmBtn: "Confirm",
      dialogPhone: "Mobile Money number",
    },
    withdraw: {
      title: "Withdraw money",
      subtitle: "Withdraw your funds to your account",
      mainBalance: "Main account balance",
      insufficientBalance: "Insufficient balance. Minimum:",
      unverifiedTitle: "Account not verified",
      unverifiedDesc: "To make withdrawals, you must first verify your account. Verification secures your transactions and unlocks all features.",
      verifyButton: "Verify account",
      methodLabel: "Method",
      methodTitle: "Withdrawal method",
      mobileMoney: "Mobile Money",
      mobileMoneyDesc: "Orange, MTN, Wave, Airtel...",
      bankTransfer: "Bank transfer",
      bankTransferDesc: "To your bank account",
      comingSoon: "Coming soon",
      comingSoonDesc: "Bank transfer will be available soon.",
      formLabel: "Form",
      formTitle: "Withdrawal details",
      amountLabel: "Amount",
      countryLabel: "Country (main account)",
      operatorLabel: "Mobile Money operator",
      noOperator: "No operator available",
      registeredNumber: "Registered number",
      chooseNumber: "Choose a number",
      manageNumbers: "Manage my numbers",
      noNumberTitle: "No registered number",
      noNumbers: "No registered number",
      addNumber: "Add a number",
      phoneLabel: "Phone number",
      bankAccountLabel: "Bank account number",
      minAmount: "Minimum:",
      insufficientFunds: "Insufficient balance",
      inputAmount: "Amount entered",
      withdrawalFee: "Withdrawal fee",
      free: "Free",
      netReceive: "Net to receive",
      requestWithdrawal: "Request withdrawal",
      submitButton: "Request withdrawal",
      feeDetails: "Fee details",
      confirmTitle: "Confirm withdrawal",
      confirmMethod: "Method",
      confirmCountry: "Country",
      confirmOperator: "Operator",
      confirmNumber: "Number",
      confirmAmount: "Requested amount",
      confirmFee: "Fees",
      confirmNet: "Net to receive",
      back: "Back",
      confirm: "Confirm",
    },
    send: {
      title: "Send money",
      subtitle: "Instant transfer or via Mobile Money",
      subtitleUnverified: "Send money to a recipient",
      unverifiedTitle: "Account not verified",
      unverifiedDesc: "To send money, you must first verify your account.",
      verifyButton: "Verify account",
      sectionLabel: "Transfer",
      cardTitle: "New transfer",
      cardDesc: "Select the destination to begin",
      debitBalance: "Balance to debit",
      mainAccount: "Main Account",
      destination: "Destination",
      selectDestination: "Select destination",
      internalTransfer: "Internal Ashtech Pay Transfer",
      loading: "Loading...",
      internalFree: "Fees: 0 — Free and instant transfer",
      zeroFeeMsg: "Fees: 0 — Free and instant transfer",
      recipientLabel: "Email, phone or username",
      amountLabel: "Amount",
      sendButton: "Send",
      chooseDestFirst: "Choose a destination first",
      noOperator: "No operator available for this country",
      operatorLabel: "Operator",
      recipientName: "Recipient name",
      recipientPhone: "Phone number",
      amountToSend: "Amount to send",
      sendAmountLabel: "Amount to send",
      minAmount: "Minimum amount:",
      maxAmount: "Maximum amount:",
      currencyMismatch: "Unauthorized transaction — Selected account is in",
      currencyMismatchMid: "but",
      currencyMismatchEnd: "uses",
      currencyMismatchFix: "Please choose the correct account.",
      sendAmount: "Send",
      yourBalance: "Your balance",
      summaryLabel: "Summary",
      summary: "Summary",
      amountSent: "Amount to send",
      summaryAmount: "Amount to send",
      fees: "Fees",
      summaryFee: "Fees",
      netSent: "Net sent",
      summaryNet: "Net sent",
      balanceAfter: "Balance after transfer",
      insufficientBalance: "Insufficient balance",
      benefitsLabel: "Benefits",
      advantages: "Benefits",
      benefitFree: "Free — no fees",
      advantageFree: "Free — no fees",
      benefitInstant: "Instant — immediate credit",
      advantageInstant: "Instant — immediate credit",
      benefitSecure: "Secure — verified account",
      advantageSecure: "Secure — verified account",
      free: "Free",
      confirmInternalTitle: "Confirm internal transfer",
      confirmRecipient: "Recipient",
      confirmDebitAccount: "Debited account",
      confirmAmount: "Amount",
      confirmFees: "Fees",
      confirmFee: "Fees",
      confirmFreeLabel: "Free",
      confirmExternalTitle: "Confirm transfer",
      confirmNumber: "Number",
      confirmPhone: "Number",
      confirmCountryOperator: "Country / Operator",
      confirmAmountSent: "Amount sent",
      confirmSentAmount: "Amount sent",
      confirmFeePercent: "Fees",
      confirmNetReceived: "Net received",
      back: "Back",
      confirm: "Confirm",
    },
    settings: {
      title: "Settings",
      subtitle: "Manage your account settings",
      profileSection: "Profile",
      verificationSection: "Verification",
      appearanceSection: "Appearance",
      financesSection: "Finances",
      notificationsSection: "Notifications",
      securitySection: "Security & API",
      dangerSection: "Danger Zone",
      verified: "Verified",
      pendingVerif: "Pending",
      unverified: "Unverified",
      emailLabel: "Email",
      phoneLabel: "Phone",
      countryLabel: "Country",
      kycTitle: "KYC Verification",
      kycVerified: "Verified",
      kycPending: "Pending",
      kycComplete: "Complete",
      themeLabel: "Theme",
      themeLight: "Light",
      themeDark: "Dark",
      withdrawalNumbers: "Withdrawal numbers",
      manage: "Manage",
      notifPreferences: "Notification preferences",
      notifEmail: "Email notifications",
      notifEmailDesc: "Email alerts",
      notifPush: "Push notifications",
      notifPushDesc: "Browser alerts",
      notifSms: "SMS notifications",
      notifSmsDesc: "SMS alerts",
      notifMarketing: "Marketing communications",
      notifMarketingDesc: "News and promotions",
      savePrefs: "Save",
      prefsSaved: "Preferences saved",
      prefsSavedDesc: "Your notification preferences have been saved.",
      changePassword: "Change password",
      currentPassword: "Current password",
      newPassword: "New password",
      confirmPassword: "Confirm password",
      changePasswordBtn: "Change password",
      apiKeysLabel: "API Keys & Developer",
      deleteAccount: "Delete my account",
      deleteAccountDesc: "Irreversible action",
      deleteDialogTitle: "Permanently delete your account",
      deleteDialogDesc: "This action is irreversible and will delete all your data.",
      deleteConfirmLabel: "Enter your username to confirm",
      deleteConfirmHint: "Type",
      deleteConfirmHint2: "to confirm",
      cancelDelete: "No, cancel",
      confirmDelete: "Yes, delete my account",
      profileUpdated: "Profile updated",
      profileUpdatedDesc: "Name saved successfully.",
      accountDeleted: "Account deleted",
      accountDeletedDesc: "Your account has been deleted successfully.",
    },
    common: {
      confirm: "Confirm",
      cancel: "Cancel",
      back: "Back",
      save: "Save",
      edit: "Edit",
      delete: "Delete",
      close: "Close",
      loading: "Loading...",
      error: "Error",
      success: "Success",
      amount: "Amount",
      currency: "Currency",
      country: "Country",
      operator: "Operator",
      phone: "Phone",
      name: "Name",
      email: "Email",
      search: "Search",
      filter: "Filter",
      export: "Export",
      status: "Status",
      date: "Date",
      type: "Type",
      completed: "Completed",
      pending: "Pending",
      failed: "Failed",
      all: "All",
    },
    notifications: {
      title: "Notifications",
      markAllRead: "Mark all as read",
      noNotifications: "No notifications",
    },
    kyc: {
      title: "KYC Verification",
      subtitle: "Verify your identity to unlock all features",
      statusApproved: "Account verified",
      statusApprovedDesc: "Your account is fully verified. You have access to all features.",
      statusPending: "Verification in progress",
      statusPendingDesc: "Your request is being reviewed. You will be notified by email once verification is complete.",
      statusRejected: "Verification rejected",
      statusRejectedDesc: "Your request was rejected. Please submit new documents.",
      statusRejectedReason: "Reason:",
      statusNone: "Verification not completed",
      statusNoneDesc: "Complete your KYC verification to access send, withdrawal and transfer features.",
      identitySection: "Identity",
      identityTitle: "Personal information",
      identityDesc: "This information comes from your account and cannot be modified here",
      fullNameLabel: "Full name",
      emailLabel: "Email address",
      phoneLabel: "Phone number",
      countryLabel: "Country",
      cityLabel: "City *",
      cityPlaceholder: "Ex: Douala",
      postalCodeLabel: "Postal code *",
      postalCodePlaceholder: "Ex: 00237",
      notFilled: "Not provided",
      documentsSection: "Documents",
      documentsTitle: "Identity document",
      documentsDesc: "Upload a copy of your valid identity document",
      documentTypeLabel: "Document type *",
      documentTypePlaceholder: "Choose document type",
      documentNumberLabel: "Document number *",
      documentNumberPlaceholder: "Ex: 123456789",
      frontLabel: "Document front *",
      frontDesc: "Click to upload the front",
      backLabel: "Document back *",
      backDesc: "Click to upload the back",
      selfieLabel: "Selfie with document *",
      selfieDesc: "Take a selfie holding your document",
      uploading: "Uploading...",
      uploaded: "Uploaded",
      fileFormat: "JPG, PNG, WebP - Max 5 MB",
      activitySection: "Activity",
      activityTitle: "Business information",
      activityDesc: "Describe your professional or business activity",
      businessTypeLabel: "Business type *",
      businessTypePlaceholder: "Choose business type",
      businessTypePhysical: "Physical commerce / In-person service",
      businessTypeOnline: "Online commerce / Digital service",
      businessCategoryLabel: "Business category *",
      categoryChoose: "Choose category",
      categorySelectType: "Select type first",
      categorySearch: "Search category...",
      categoryEmpty: "No category found.",
      businessDescLabel: "Business description *",
      businessDescPlaceholder: "Briefly describe your activity, the products or services you offer...",
      wordsOf: "/ 250 words",
      requiredDocs: "Required documents",
      docFront: "Front of identity document",
      docBack: "Back of identity document",
      docSelfie: "Selfie with document",
      submitButton: "Submit for verification",
      submitting: "Submitting...",
      toastSubmitted: "Request submitted",
      toastSubmittedDesc: "Your verification request is being processed.",
      toastError: "Error",
      toastFileTypeError: "File type not allowed",
      toastFileTypeDesc: "Please use a JPG, PNG or WebP file",
      toastFileSizeError: "File too large",
      toastFileSizeDesc: "Maximum size is 5 MB",
      toastFileUploaded: "File uploaded",
      toastFileUploadedDesc: "The file was uploaded successfully",
      toastUploadError: "Upload error",
      toastRequiredFields: "Required fields",
      toastRequiredFieldsDesc: "Please fill in all required fields (city and postal code included)",
      toastDescTooLong: "Description too long",
      toastDescTooLongPre: "Description cannot exceed 250 words (currently ",
      toastDescTooLongSuf: " words)",
      toastDocsRequired: "Documents required",
      toastDocsRequiredDesc: "Please upload all required documents",
    },
    withdrawalNumbers: {
      title: "Withdrawal numbers",
      subtitle: "Manage your phone numbers for withdrawals (max. 2)",
      addButton: "Add a number",
      registeredNumbers: "Registered numbers",
      noNumbers: "No withdrawal number registered",
      noNumbersHint: "Add a number to be able to make withdrawals",
      pendingApproval: "Pending approval",
      requestHistory: "Request history",
      actionAdd: "Add",
      actionUpdate: "Update",
      actionDelete: "Delete",
      statusPending: "Pending",
      statusApproved: "Approved",
      statusRejected: "Rejected",
      noteLabel: "Note:",
      toastDeleteTitle: "Request sent",
      toastDeleteDesc: "Your deletion request has been sent for approval",
      toastError: "Error",
    },
    addWithdrawalNumber: {
      title: "Add a withdrawal number",
      subtitle: "Select your operator and enter your number",
      chooseOperator: "Choose an operator",
      operatorsFor: "Available operators for",
      yourCountry: "your country",
      noOperators: "No operator available for your country",
      contactSupport: "Contact support for more information",
      numberInfo: "Number information",
      numberInfoDescPre: "Enter the ",
      numberInfoDescSuf: " number for withdrawals",
      phoneLabel: "Phone number",
      labelLabel: "Label (optional)",
      labelPlaceholder: "e.g.: Primary, Secondary",
      saveButton: "Save number",
      toastAdded: "Number added",
      toastAddedDesc: "The withdrawal number has been registered successfully",
      toastError: "Error",
      toastErrorDesc: "Please select an operator and enter a number",
    },
    editWithdrawalNumber: {
      title: "Edit withdrawal number",
      subtitle: "Modification requires admin approval",
      approvalRequired: "Approval required",
      approvalDesc: "Any withdrawal number modification must be approved by an administrator for security reasons.",
      chooseOperator: "Choose an operator",
      operatorsFor: "Available operators for",
      yourCountry: "your country",
      noOperators: "No operator available for your country",
      numberInfo: "Number information",
      numberInfoDescPre: "Edit the information for your ",
      phoneLabel: "Phone number",
      labelLabel: "Label (optional)",
      labelPlaceholder: "e.g.: Primary, Secondary",
      submitButton: "Submit modification request",
      toastSent: "Request sent",
      toastSentDesc: "Your modification request has been sent for approval",
      toastError: "Error",
      toastErrorDesc: "Please fill in all fields",
    },
    apiKeys: {
      title: "API Key",
      subtitle: "Integrate Ashtech Pay directly into your application",
      notVerifiedTitle: "Account not verified",
      notVerifiedDesc: "Your account must be <strong>verified (KYC)</strong> before you can access the API. Complete the identity verification, then contact the administrator to activate your keys.",
      goKycButton: "Verify my identity",
      kycStep: "Step 1: KYC verification · Step 2: API activation by administrator",
      apiNotEnabledTitle: "API access not enabled",
      apiNotEnabledDesc: "Your account is <strong>verified</strong>, but API access has not yet been enabled by the administrator. Contact us to request activation of your keys.",
      contactAdminButton: "Contact administrator",
      apiActiveStatus: "KYC validated · Pending API activation by administrator",
      apiBannerTitle: "API enabled",
      apiBannerDesc: "Your API access is active. Use your keys below to integrate Ashtech Pay into your application.",
      modeActive: "Active",
      hostedPageDesc: "Payment link hosted by Ashtech Pay",
      sdkDesc: "Direct integration without redirect",
      step1Label: "1. Configure",
      step1Desc: "Enter your redirect URLs and generate your keys.",
      step2Label: "2. Create a link",
      step2Desc: "Call the API to create a unique payment link.",
      step3Label: "3. Customer pays",
      step3Desc: "The customer pays on the hosted Ashtech Pay page.",
      configSection: "Configuration",
      configTitle: "Redirect URLs",
      successUrlDesc: "URL to which the customer will be redirected after a successful payment.",
      cancelUrlDesc: "URL to which the customer will be redirected if payment fails or is cancelled.",
      webhookLabel: "Webhook URL (notify_url)",
      webhookBadge: "Automatic",
      webhookDesc: "Your server will automatically receive a POST notification for each confirmed or failed Hosted Page payment — without you having to specify it in each link.",
      saveUrlsButton: "Save URLs",
      savingButton: "Saving...",
      generatingButton: "Generating...",
      keysSection: "Generated keys",
      keysActive: "Active",
      regenerateKeys: "Regenerate all keys",
      regenerateWarning: "Warning — regenerating keys will invalidate current keys.",
      docButton: "Documentation",
      sdkAuthSection: "Authentication",
      sdkAuthTitle: "Your API key",
      sdkAuthDesc: "Use this key to authenticate all your requests to the Ashtech Pay API. Never share it publicly.",
      sdkLoading: "Loading…",
      sdkHide: "Hide",
      sdkShow: "Show",
      sdkCopy: "Copy",
      sdkRegenerateWarning: "If you regenerate the key, the old one will be immediately invalidated.",
      sdkRegenerate: "Regenerate",
      sdkDocsButton: "Integration documentation",
      sdkExampleTitle: "Quick example",
      toastKeyCopied: "Key copied",
      toastKeyCopiedDescSuf: " copied to clipboard.",
      toastRegenerated: "Key regenerated",
      toastRegeneratedDesc: "Your new API key is ready. Update your integration.",
      toastError: "Error",
      toastImpossibleRegen: "Unable to regenerate the key.",
      toastConfigSaved: "Configuration saved",
      toastConfigSavedDesc: "Your Hosted Page API keys are ready.",
      toastImpossibleSave: "Unable to save.",
      toastApiKeyCopied: "Key copied",
      toastApiKeyCopiedDesc: "The API key has been copied to the clipboard.",
    },
    kycVerified: {
      title: "Account already verified",
      desc: "Your account is already verified. You have access to all platform features.",
      updateQuestion: "Would you like to update your KYC information?",
      noBack: "No, return to dashboard",
      yesUpdate: "Yes, update",
    },
    wallets: {
      title: "My Accounts",
      subtitle: "Manage your multi-currency wallets",
      addAccount: "Add account",
      alertDesc: "Received payments are credited to the wallet matching the payment currency. Use conversion to transfer between your accounts.",
      walletsLabel: "Wallets",
      principal: "Primary",
      balance: "Balance",
      requestConversion: "Request conversion",
      disableTooltip: "Disable this account",
      disableTitle: "Disable this account",
      conversionDone: "Conversion done",
      conversionDoneDescPre: "Your conversion of ",
      conversionDoneDescMid: " to ",
      conversionDoneDescSuf: " was processed successfully.",
      convertDialogTitle: "Currency conversion",
      convertDialogDesc: "Convert your funds instantly. Conversion fees are applied automatically.",
      fromAccount: "Source account (to debit)",
      toAccount: "Target account (to credit)",
      convertAmountLabel: "Amount to convert",
      insufficientPre: "Insufficient balance. Available: ",
      grossAmount: "Gross amount",
      conversionFee: "Conversion fee (estimated)",
      youReceiveAbout: "You will receive approximately",
      rateNote: "The final rate may vary slightly.",
      cancel: "Cancel",
      convertNow: "Convert now",
      addDialogTitle: "Add account",
      addDialogDesc: "Open a new account in another currency. The account will be initialized with a balance of 0.",
      currencyLabel: "Currency",
      chooseCurrency: "Choose a currency",
      create: "Create",
      disableWithBalancePre: "This account ",
      disableWithBalanceMid: " contains a balance of ",
      disableWithBalanceSuf: ". This amount will be permanently lost if you disable this account. Are you sure you want to continue?",
      disableLose: "This amount will be permanently lost",
      disableNoBalancePre: "Do you want to disable account ",
      disableNoBalanceSuf: "? This account will be removed from your list.",
      disableButton: "Disable and lose balance",
      disableButtonSimple: "Disable",
      toastCreated: "Account created",
      toastCreatedDescPre: "Account ",
      toastCreatedDescSuf: " created successfully",
      toastDisabled: "Account disabled",
      toastDisabledDescPre: "Account ",
      toastDisabledDescSuf: " has been deleted",
      toastError: "Error",
    },
    support: {
      title: "Support",
      subtitle: "How can we help you?",
      contactSection: "Contact us",
      chatTitle: "Live chat",
      chatDesc: "Response in a few minutes",
      whatsappChannelTitle: "Join our WhatsApp channel",
      whatsappChannelDesc: "Stay informed of the latest Ashtech Pay news and updates",
      joinChannel: "Join the channel",
      myConversationsSection: "My conversations",
      seeAll: "See all conversations",
      faqSection: "Frequently asked questions",
      faq1Q: "How do I top up my account?",
      faq1A: "Go to Deposit and choose your preferred payment method (Mobile Money or Crypto).",
      faq2Q: "How long does a withdrawal take?",
      faq2A: "Withdrawals are processed within 24 business hours. Mobile Money is generally faster (a few minutes).",
      faq3Q: "How do I create a payment link?",
      faq3A: "Go to 'My links', click 'New link' and fill in the form.",
      faq4Q: "What are the transaction fees?",
      faq4A: "Transfers between Ashtech Pay users are free. Fees apply for external withdrawals.",
      supportOnline: "Support online",
      supportOffline: "Support offline",
      close: "Close",
      newChat: "New",
      myConversations: "My conversations",
      noConversations: "No conversations",
      startConversation: "Start a conversation",
      noMessages: "No messages",
      closedConversation: "This conversation is closed",
      messagePlaceholder: "Write your message...",
      newConversationTitle: "New conversation",
      newConversationDesc: "Describe your problem and our team will respond quickly.",
      subjectLabel: "Subject *",
      subjectPlaceholder: "Ex: Deposit issue",
      messageLabel: "Message *",
      messagePlaceholder2: "Describe your problem in detail...",
      send: "Send",
      sending: "Sending...",
      cancel: "Cancel",
      requiredFields: "Required fields",
      requiredFieldsDesc: "Please fill in all fields.",
      ticketClosed: "Ticket closed",
      ticketClosedDesc: "The conversation has been closed.",
      errorCreate: "Unable to create the ticket.",
      errorSend: "Unable to send the message.",
      statusOpen: "Open",
      statusInProgress: "In progress",
      statusResolved: "Resolved",
      statusClosed: "Closed",
    },
    links: {
      title: "My payment links",
      subtitle: "Manage your links and analyze your performance",
      newLink: "New link",
      recentLinks: "Recent links",
      allYourLinks: "All your",
      linksWord: "links",
      freeAmount: "Free amount",
      clicks: "clicks",
      showLess: "Show less",
      seeMore: "See",
      moreLinks: "more",
      allLinks: "All links",
      periodToday: "Today",
      periodWeek: "This week",
      periodMonth: "This month",
      periodLastMonth: "Last month",
      periodYear: "This year",
      periodAll: "All",
      statClicks: "Link clicks",
      statTransactions: "Transactions",
      statCollected: "Total collected",
      statConversion: "Conversion rate",
      trendVsPrevious: "+12% vs previous period",
      trendTransactions: "+8% vs previous period",
      tabAnalytics: "Analytics",
      tabPayments: "Payments",
      tabLinks: "Links",
      analyticsSection: "Analytics",
      chartTitle: "Collected amounts by period",
      chartDescWeek: "This week",
      chartDescMonths: "Last 6 months",
      geoSection: "Geography",
      geoTitle: "Main countries",
      methodsSection: "Methods",
      methodsTitle: "Payment sources",
      methodsDesc: "Payment breakdown by method",
      methodMobileMoney: "Mobile Money",
      methodCard: "Bank card",
      methodPaypal: "PayPal",
      methodOther: "Other",
      noData: "No data",
      paymentsSection: "Payments",
      paymentsTitle: "Received payments",
      paymentsDesc: "All payments made through your links",
      noPayments: "No payment received yet",
      statusCompleted: "Completed",
      statusPending: "Pending",
      statusFailed: "Failed",
      amountPaid: "Amount paid:",
      fee: "fee",
      ref: "Ref:",
      allLinksSection: "All links",
      noLinks: "No payment link created",
      createFirstLink: "Create your first link",
      deactivate: "Deactivate",
      activate: "Activate",
      deleteConfirm: "Are you sure you want to permanently delete this link?",
      qrModalDesc: "Scan this code to access the payment link",
      copyLink: "Copy link",
      toastCopied: "Link copied",
      toastCopiedDesc: "The link has been copied to clipboard",
      toastDeleted: "Link deleted",
      toastDeletedDesc: "The link was permanently deleted",
      toastPdf: "PDF downloaded",
      toastPdfDesc: "The report was generated successfully",
      toastLinkCreated: "Link created",
      toastLinkCreatedDesc: "Your payment link was created successfully",
      toastLinkUpdated: "Link updated",
      toastLinkUpdatedDesc: "The changes have been saved",
      toastError: "Error",
      toastUploadError: "Image upload error",
      createDialogTitle: "Create a payment link",
      createDialogDesc: "Create a shareable link to receive payments",
      editDialogTitle: "Edit payment link",
      editDialogDesc: "Edit your link information",
      formTitle: "Title *",
      formTitlePlaceholder: "Ex: Order payment #123",
      formDesc: "Description (optional)",
      formDescPlaceholder: "Payment description...",
      formSlug: "Custom URL (optional)",
      formSlugHint: "Leave blank to auto-generate",
      formImage: "Image (optional)",
      formImageDesc: "This image will appear on the payment page",
      formImageUpload: "Choose an image",
      formImageAdd: "Click to add an image",
      formPdf: "PDF link (optional)",
      formPdfDesc: "This PDF will be sent to the customer only after a successful payment",
      formPdfDelivery: "PDF delivery after payment",
      formPdfDeliveryDesc: "The customer will receive this PDF link after paying successfully",
      formAmountType: "Amount type",
      formFixed: "Fixed amount set by you",
      formFree: "Free amount chosen by payer",
      formAmount: "Amount",
      formExpiry: "Expiry date (optional)",
      formRedirect: "Redirect URL after payment (optional)",
      formCreateButton: "Create link",
      formSaveButton: "Save changes",
      pdfReportTitle: "Payment link report",
      pdfFixed: "Fixed amount",
      pdfFree: "Variable",
      pdfActive: "Active",
      pdfInactive: "Inactive",
      qrTitle: "QR Code",
      chartAmount: "Amount",
      pmtShort: "pmt.",
      cancel: "Cancel",
    },
    login: {
      title: "Log in",
      emailLabel: "Email or Phone",
      emailPlaceholder: "youremail@example.com or +237...",
      passwordLabel: "Password",
      forgotPassword: "Forgot password?",
      submit: "Log in",
      submitting: "Logging in...",
      noAccount: "Don't have an account?",
      createAccount: "Create an account",
      home: "Home",
      toastSuccess: "Login successful",
      toastSuccessDescPre: "Welcome, ",
      toastError: "Login error",
      toastErrorDesc: "Invalid credentials",
    },
    register: {
      title: "Create an account",
      fullName: "Full name",
      username: "Username",
      email: "Email",
      phone: "Phone",
      country: "Country",
      password: "Password",
      confirmPassword: "Confirm password",
      submit: "Create my account",
      submitting: "Creating...",
      hasAccount: "Already have an account?",
      login: "Log in",
      home: "Home",
      toastSuccess: "Registration successful",
      toastSuccessDescPre: "Welcome to Ashtech Pay, ",
      toastError: "Registration error",
      toastErrorDesc: "An error occurred",
      errorNoCountry: "Please select a country",
      errorCountry: "Error",
      passwordMinError: "Password must be at least 6 characters",
      passwordMismatch: "Passwords do not match",
    },
  },
} as const;

export type Translations = typeof translations.fr;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("ashtech_language");
    return (saved === "en" || saved === "fr") ? saved : "fr";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("ashtech_language", lang);
  };

  const t = translations[language] as Translations;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used inside LanguageProvider");
  return ctx;
}
