import session from "express-session";

type QueryResult = { rows: any[] };
type QueryPool = {
  query: (text: string, values?: unknown[]) => Promise<QueryResult>;
};

type TokenDedupOptions = {
  pool: QueryPool;
  isMysql: boolean;
  tableName?: string;
  errorLog?: (error: Error) => void;
};

/**
 * Bearer-authenticated browsers can create a fresh Express SID when they do
 * not retain the session cookie. Keep the SID generated by express-session as
 * an implementation detail, but persist all writes for the same user/token
 * pair into one durable row.
 *
 * The token timestamp is part of the signed token and identifies one login
 * device. userId is included as a second key so a timestamp collision can
 * never merge two accounts.
 */
export function wrapSessionStoreWithTokenDedup(
  store: session.Store,
  options: TokenDedupOptions,
): session.Store {
  const originalSet = store.set.bind(store);
  const originalDestroy = store.destroy.bind(store);
  const tableName = options.tableName || "session";
  const errorLog = options.errorLog || (() => undefined);

  (store as any).set = (
    sid: string,
    sessionData: session.SessionData,
    callback: (error?: any) => void = () => undefined,
  ) => {
    void (async () => {
      const userId = sessionData?.userId;
      const tokenIssuedAt = sessionData?.tokenIssuedAt;

      if (userId == null || tokenIssuedAt == null) {
        await new Promise<void>((resolve, reject) => {
          originalSet(sid, sessionData, (error?: any) => error ? reject(error) : resolve());
        });
        callback();
        return;
      }

      let existingSid: string | null = null;
      let existingData: Record<string, any> | null = null;
      try {
        const result = options.isMysql
          ? await options.pool.query(
              `SELECT sid, sess
                 FROM \`${tableName}\`
                WHERE JSON_UNQUOTE(JSON_EXTRACT(sess, '$.userId')) = ?
                  AND JSON_UNQUOTE(JSON_EXTRACT(sess, '$.tokenIssuedAt')) = ?
                ORDER BY (sid = ?) DESC, expire DESC
                LIMIT 1`,
              [String(userId), String(tokenIssuedAt), sid],
            )
          : await options.pool.query(
              `SELECT sid, sess
                 FROM "${tableName}"
                WHERE sess->>'userId' = $1
                  AND sess->>'tokenIssuedAt' = $2
                ORDER BY (sid = $3) DESC, expire DESC
                LIMIT 1`,
              [String(userId), String(tokenIssuedAt), sid],
            );

        const row = result.rows?.[0];
        if (row?.sid) {
          existingSid = String(row.sid);
          try {
            existingData = typeof row.sess === "string"
              ? JSON.parse(row.sess)
              : (row.sess || {});
          } catch {
            existingData = null;
          }
        }
      } catch (error) {
        // A deduplication lookup must never prevent a valid login/session write.
        errorLog(error instanceof Error ? error : new Error(String(error)));
      }

      const targetSid = existingSid || sid;
      // Preserve verified admin factors when a cookie-less ordinary request
      // rewrites the canonical session with a fresh ephemeral session object.
      // Explicit factor updates still win because the incoming object contains
      // the newly verified values.
      const incomingData = sessionData as session.SessionData & Record<string, any>;
      const mergedData = existingData
        ? {
            ...existingData,
            ...incomingData,
            ...(["_avs", "_avsIp", "_pav", "_pavVerifiedAt", "_ppv", "_ppvIp"]
              .filter((key) => incomingData[key] !== undefined)
              .reduce((acc, key) => ({ ...acc, [key]: incomingData[key] }), {})),
          }
        : sessionData;

      await new Promise<void>((resolve, reject) => {
        originalSet(targetSid, mergedData, (error?: any) => error ? reject(error) : resolve());
      });

      if (targetSid !== sid) {
        await new Promise<void>((resolve, reject) => {
          originalDestroy(sid, (error?: any) => error ? reject(error) : resolve());
        });
      }

      // Clean older duplicates left by the previous cookie-less behavior.
      try {
        if (options.isMysql) {
          await options.pool.query(
            `DELETE FROM \`${tableName}\`
              WHERE JSON_UNQUOTE(JSON_EXTRACT(sess, '$.userId')) = ?
                AND JSON_UNQUOTE(JSON_EXTRACT(sess, '$.tokenIssuedAt')) = ?
                AND sid <> ?`,
            [String(userId), String(tokenIssuedAt), targetSid],
          );
        } else {
          await options.pool.query(
            `DELETE FROM "${tableName}"
              WHERE sess->>'userId' = $1
                AND sess->>'tokenIssuedAt' = $2
                AND sid <> $3`,
            [String(userId), String(tokenIssuedAt), targetSid],
          );
        }
      } catch (error) {
        errorLog(error instanceof Error ? error : new Error(String(error)));
      }

      callback();
    })().catch((error) => {
      errorLog(error instanceof Error ? error : new Error(String(error)));
      callback(error);
    });
  };

  return store;
}