import session from "express-session";

type QueryResult = { rows: any[] };
type QueryPool = {
  query: (text: string, values?: unknown[]) => Promise<QueryResult>;
};

type TokenDedupOptions = {
  pool: QueryPool;
  isMysql: boolean;
  tableName?: string;
  errorLog?: (error: Error) => void;
  maxDevices?: number;
  onDeviceEvicted?: (event: {
    userId: string;
    sid: string;
    tokenIssuedAt: number | null;
  }) => void | Promise<void>;
};

/**
 * Bearer-authenticated browsers can create a fresh Express SID when they do
 * not retain the session cookie. Keep the SID generated by express-session as
 * an implementation detail, but persist all writes for the same user/token
 * pair into one durable row.
 *
 * The token timestamp is part of the signed token and identifies one login
 * device. userId is included as a second key so a timestamp collision can
 * never merge two accounts.
 */
export function wrapSessionStoreWithTokenDedup(
  store: session.Store,
  options: TokenDedupOptions,
): session.Store {
  const originalSet = store.set.bind(store);
  const originalDestroy = store.destroy.bind(store);
  const tableName = options.tableName || "session";
  const errorLog = options.errorLog || (() => undefined);

  (store as any).set = (
    sid: string,
    sessionData: session.SessionData,
    callback: (error?: any) => void = () => undefined,
  ) => {
    void (async () => {
      const userId = sessionData?.userId;
      const tokenIssuedAt = sessionData?.tokenIssuedAt;

      if (userId == null || tokenIssuedAt == null) {
        await new Promise<void>((resolve, reject) => {
          originalSet(sid, sessionData, (error?: any) => error ? reject(error) : resolve());
        });
        callback();
        return;
      }

      let existingSid: string | null = null;
      let existingData: Record<string, any> | null = null;
      try {
        const result = options.isMysql
          ? await options.pool.query(
              `SELECT sid, sess
                 FROM \`${tableName}\`
                WHERE JSON_UNQUOTE(JSON_EXTRACT(sess, '$.userId')) = ?
                  AND JSON_UNQUOTE(JSON_EXTRACT(sess, '$.tokenIssuedAt')) = ?
                ORDER BY (sid = ?) DESC, expire DESC
                LIMIT 1`,
              [String(userId), String(tokenIssuedAt), sid],
            )
          : await options.pool.query(
              `SELECT sid, sess
                 FROM "${tableName}"
                WHERE sess->>'userId' = $1
                  AND sess->>'tokenIssuedAt' = $2
                ORDER BY (sid = $3) DESC, expire DESC
                LIMIT 1`,
              [String(userId), String(tokenIssuedAt), sid],
            );

        const row = result.rows?.[0];
        if (row?.sid) {
          existingSid = String(row.sid);
          try {
            existingData = typeof row.sess === "string"
              ? JSON.parse(row.sess)
              : (row.sess || {});
          } catch {
            existingData = null;
          }
        }
      } catch (error) {
        // A deduplication lookup must never prevent a valid login/session write.
        errorLog(error instanceof Error ? error : new Error(String(error)));
      }

      const targetSid = existingSid || sid;
      // Preserve verified admin factors when a cookie-less ordinary request
      // rewrites the canonical session with a fresh ephemeral session object.
      // Explicit factor updates still win because the incoming object contains
      // the newly verified values.
      const incomingData = sessionData as session.SessionData & Record<string, any>;
      const mergedData = existingData
        ? {
            ...existingData,
            ...incomingData,
            ...(["_avs", "_avsIp", "_pav", "_pavVerifiedAt", "_ppv", "_ppvIp"]
              .filter((key) => incomingData[key] !== undefined)
              .reduce((acc, key) => ({ ...acc, [key]: incomingData[key] }), {})),
          }
        : sessionData;

      await new Promise<void>((resolve, reject) => {
        originalSet(targetSid, mergedData, (error?: any) => error ? reject(error) : resolve());
      });

      if (targetSid !== sid) {
        await new Promise<void>((resolve, reject) => {
          originalDestroy(sid, (error?: any) => error ? reject(error) : resolve());
        });
      }

      // Clean older duplicates left by the previous cookie-less behavior.
      try {
        if (options.isMysql) {
          await options.pool.query(
            `DELETE FROM \`${tableName}\`
              WHERE JSON_UNQUOTE(JSON_EXTRACT(sess, '$.userId')) = ?
                AND JSON_UNQUOTE(JSON_EXTRACT(sess, '$.tokenIssuedAt')) = ?
                AND sid <> ?`,
            [String(userId), String(tokenIssuedAt), targetSid],
          );
        } else {
          await options.pool.query(
            `DELETE FROM "${tableName}"
              WHERE sess->>'userId' = $1
                AND sess->>'tokenIssuedAt' = $2
                AND sid <> $3`,
            [String(userId), String(tokenIssuedAt), targetSid],
          );
        }
      } catch (error) {
        errorLog(error instanceof Error ? error : new Error(String(error)));
      }

      // Keep a hard upper bound on authenticated devices. This runs only when
      // a token is first persisted, not on every subsequent session update.
      // The token timestamp is the device identity; the oldest timestamp is
      // the device that must be evicted first.
      const maxDevices = options.maxDevices;
      if (!existingSid && maxDevices && maxDevices > 0) {
        try {
          const result = options.isMysql
            ? await options.pool.query(
                `SELECT sid, sess, expire
                   FROM \`${tableName}\`
                  WHERE JSON_UNQUOTE(JSON_EXTRACT(sess, '$.userId')) = ?`,
                [String(userId)],
              )
            : await options.pool.query(
                `SELECT sid, sess, expire
                   FROM "${tableName}"
                  WHERE sess->>'userId' = $1`,
                [String(userId)],
              );

          const now = Date.now();
          const sessionRows = (result.rows || []).flatMap((row: any) => {
            let data: Record<string, any>;
            try {
              data = typeof row.sess === "string" ? JSON.parse(row.sess) : (row.sess || {});
            } catch {
              return [];
            }
            const expiresAt = new Date(row.expire).getTime();
            if (Number.isFinite(expiresAt) && expiresAt <= now) return [];
            return [{
              sid: String(row.sid),
              data,
              age: getSessionDeviceAge(data, row.expire),
              expire: expiresAt,
            }];
          });

          // Old cookie-less requests could leave more than one SID for the
          // same user/token identity. Clean aliases without counting them as
          // additional devices or revoking the token they share.
          const deviceGroups = new Map<string, typeof sessionRows>();
          for (const row of sessionRows) {
            const tokenTs = Number(row.data?.tokenIssuedAt);
            const identity = Number.isFinite(tokenTs) && tokenTs > 0
              ? `token:${tokenTs}`
              : `sid:${row.sid}`;
            const group = deviceGroups.get(identity) || [];
            group.push(row);
            deviceGroups.set(identity, group);
          }

          const devices = [...deviceGroups.values()].map((group) => {
            // Prefer this request's SID, otherwise preserve the freshest row's
            // admin/session factors when removing legacy duplicate SIDs.
            group.sort((a, b) =>
              Number(b.sid === targetSid) - Number(a.sid === targetSid) ||
              b.expire - a.expire
            );
            const canonical = group[0];
            return {
              rows: group,
              age: Math.min(...group.map((row) => row.age)),
              canonical,
            };
          });

          for (const device of devices) {
            for (const duplicate of device.rows.slice(1)) {
              if (options.isMysql) {
                await options.pool.query(
                  `DELETE FROM \`${tableName}\` WHERE sid = ?`,
                  [duplicate.sid],
                );
              } else {
                await options.pool.query(
                  `DELETE FROM "${tableName}" WHERE sid = $1`,
                  [duplicate.sid],
                );
              }
            }
          }

          if (devices.length > maxDevices) {
            devices.sort((a, b) => b.age - a.age);
            const evictedDevices = devices.slice(maxDevices).sort((a, b) => a.age - b.age);
            for (const device of evictedDevices) {
              const tokenIssuedAt = Number(device.canonical.data?.tokenIssuedAt);
              let revoked = true;
              for (const evicted of device.rows) {
                try {
                  // Persist the token revocation before removing its session
                  // row; a stateless Bearer token must not recreate it later.
                  await options.onDeviceEvicted?.({
                    userId: String(userId),
                    sid: evicted.sid,
                    tokenIssuedAt: Number.isFinite(tokenIssuedAt) && tokenIssuedAt > 0
                      ? tokenIssuedAt
                      : null,
                  });
                } catch (error) {
                  errorLog(error instanceof Error ? error : new Error(String(error)));
                  revoked = false;
                  break;
                }
              }
              if (!revoked) {
                // Keep the device if its Bearer token could not be revoked. A
                // later session write will retry once persistence is healthy.
                continue;
              }

              for (const evicted of device.rows) {
                if (options.isMysql) {
                  await options.pool.query(
                    `DELETE FROM \`${tableName}\` WHERE sid = ?`,
                    [evicted.sid],
                  );
                } else {
                  await options.pool.query(
                    `DELETE FROM "${tableName}" WHERE sid = $1`,
                    [evicted.sid],
                  );
                }
              }
            }
          }
        } catch (error) {
          // Device-limit enforcement must not turn a valid login into a 500.
          errorLog(error instanceof Error ? error : new Error(String(error)));
        }
      }

      callback();
    })().catch((error) => {
      errorLog(error instanceof Error ? error : new Error(String(error)));
      callback(error);
    });
  };

  return store;
}

function getSessionDeviceAge(sessionData: Record<string, any>, expire: unknown): number {
  const tokenIssuedAt = Number(sessionData?.tokenIssuedAt);
  if (Number.isFinite(tokenIssuedAt) && tokenIssuedAt > 0) return tokenIssuedAt;

  const loginAt = Date.parse(String(sessionData?.loginAt || ""));
  if (Number.isFinite(loginAt)) return loginAt;

  const expiresAt = new Date(expire as any).getTime();
  return Number.isFinite(expiresAt) ? expiresAt : 0;
}